<!DOCTYPE html>
<html>
<head>
    <title>Generated by ISSAT - CERTIFICAT DE SCOLARITE </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        @page {
            margin: 10px 30px;
        }
        .page-break {
            page-break-after: always;
        }

        th, td{
            font-size: 12px;
        }

        h4{
            padding: 0px;
            margin: 0px;
        }

        h6{
            margin: 2px;
            padding: 2px;
        }

        h6 span{
            font-size: 8px;
            color: #ffaa04;
        }
        #body {
            padding: 0 1cm;
        }
        #body td{
            font-size: 12px;
        }
        
        #body p{
            line-height: 20px;
        }

        .tr-title{
            padding: 10px;
            border-bottom: 1px solid #000000;
            background: ##e1e3e1;
            text-align: center;
            color: #000000;
            font-weight: bold;
        }
        input[type=checkbox] { display: inline; }
        input[type=checkbox]:before { font-family: DejaVu Sans; }
        #watermark {
            position: fixed;
            bottom:   2cm;
            width:    20cm;
            height:   20cm;
            z-index:  -1000;
            opacity: 0.2;
        }

    </style>
</head>
<body>
<div id="watermark">
    <img src="{{ asset("") }}assets/images/logo/issat.png" height="100%" width="100%" />
</div>
@if(isset($data["data"]->cycle))
    <header>
        @include("pdf.entete-certificat")
    </header>
    <main id="body">
        <p style="line-height:30px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Le Directeur de l’Institut de Formation Professionnelle SMMA & Tech Academy atteste que :</p>
            <p style="line-height:30px"><b>{{ $data["data"]->etudiant->lastname }} {{ $data["data"]->etudiant->firstname }}</b>, Mle <b>{{ $et->dossier->matriculeDossier }}</b>., est étudiant(e) en <b>@foreach($data["data"]->choice as $ch) {{ $ch->etat==1? $ch->specialite->libelleSpecialite : "" }} @endforeach</b>, Cycle <b>{{ isset($data["data"]->dossier->cycle)?$data["data"]->dossier->cycle : "inconnu" }}</b>, dans son établissement pour l’année académique <b>{{ $data["data"]->etudiant->anneacademique->numeroAnnee }}-{{ intval($data["data"]->etudiant->anneacademique->numeroAnnee)+1 }}</b></p>
            <p style="line-height:30px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;En foi de quoi le présent certificat de scolarité est établi pour servir et valoir ce que de droit./-</p>
        <br>
        <br>
        <h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Le Directeur de l'IFPSTA</h4>
    </main>
@else

    @foreach($data["data"] as $i=>$et)
        <header>
            @include("pdf.entete-certificat")
        </header>
        <main id="body">
            <p style="line-height:30px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Le Directeur de l’Institut de Formation Professionnelle SMMA & Tech Academy atteste que :</p>
            <p style="line-height:30px"><b>{{ $et->dossier->etudiant->lastname }} {{ $et->dossier->etudiant->firstname }}</b>, Mle <b>{{ $et->dossier->matriculeDossier }}</b>., est étudiant(e) en <b>@foreach($et->choice as $ch) {{ $ch->etat==1? $ch->specialite->libelleSpecialite : "" }} @endforeach</b>, Cycle <b>{{ isset($et->dossier->cycle)?$et->dossier->cycle->codeCycle : "inconnu" }}</b>, dans son établissement pour l’année académique <b>{{ $et->anneacademique->numeroAnnee }}-{{ intval($et->anneacademique->numeroAnnee)+1 }}</b></p>
            <p style="line-height:30px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;En foi de quoi le présent certificat de scolarité est établi pour servir et valoir ce que de droit./-</p>
            <br>
            <br>
            <h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Le Directeur de l'IFPSTA</h4>
        </main>

        @if($i<=count($data)-2)
            <div class="page-break"></div>
        @endif
    @endforeach
@endif
</body>
</html>