<!DOCTYPE html>
<html>
<head>
    <title>Generated by SCHOOLADMIN - Fiche de scolarité </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        @page {
            margin: 5px 12px;
        }
        .page-break {
            page-break-after: always;
        }

        h4{
            padding: 0px;
            margin: 0px;
        }

        h6{
            margin: 2px;
            padding: 2px;
        }

        h6 span{
            font-size: 14px;
            color: #ffaa04;
        }

        #body td{
            font-size: 14px;
            text-align:center;
        }

        .tr-title{
            padding: 2px;
            /*border-bottom: 1px solid #000000;*/
            background: rgba(255, 226, 0, 0.53);
            text-align: center;
        }

        .td-result{
            background: rgb(221, 222, 216);
            text-align: center;
        }

        input[type=checkbox] { display: inline; }
        input[type=checkbox]:before { font-family: DejaVu Sans; }
        #watermark {
            position: fixed;

            /** Change image dimensions**/
            /*width:    20cm;*/
            /*height:   20cm;*/

            /** Your watermark should be behind every content**/
            z-index:  -1000;
            opacity: 0.2;
            left: 6%;
        }

        .longText{
            /*transform: rotate(-90deg);*/

            /*-webkit-transform: rotate(-90deg);*/

            /*!* Firefox *!*/
            /*-moz-transform: rotate(-90deg);*/

            /*!* IE *!*/
            /*-ms-transform: rotate(-90deg);*/

            /*!* Opera *!*/
            /*-o-transform: rotate(-90deg);*/

            /*!* Internet Explorer *!*/
            /*filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);*/
        }

        #body td, #body th{
            font-size: 14px;
            text-align: center;
            height: 25px;
            font-weight: bold;
            text-transform: uppercase;
        }

        #entete td, #entete th{
            font-size: 14px;
            text-align: center;
        }

        /*tbody td{*/
        /*font-size: 5px;*/
        /*}*/

        .bg-danger{
            background-color: rgba(255, 0, 0, 0.49);
        }
        .bg-success{
            background-color: rgba(1, 203, 114, 0.51);
        }

        #header{
            font-size: 14px;
        }

        .borderStrong{
            border:2px solid #000000;
        }


    </style>
</head>
<body>
<div id="watermark">
    <img src="{{ asset("") }}assets/images/logo/issat.png" width="100%" style="margin-top: 200px"/>
</div>
<header>
    @include("pdf.entete-pv")
</header>

<hr style="background-color: #999999; border: 1px dashed #cccccc">
<h4 style="text-transform: uppercase; text-align: center">Fiche de scolarité pour le compte de l'année {{ $annee->numeroAnnee }}-{{ intval($annee->numeroAnnee)+1 }}</h4>

<main id="body" style="padding: 30px">
    @if(count($scolarite)>0)
        <table class="table" border="box" rules="all" width="100%" align="center">
            <tr class="tr-title">
                <td style="font-size: 20px">Designation</td>
                <td style="font-size: 20px">Montant</td>
            </tr>

            @foreach($specialite as $sp)
                @foreach($sp->scolarite as $i=>$scol)
                    @if($i==0)
                        <tr id="entete"  style="background-color: rgb(85,87,82); color: #ffffff">
                            <td colspan="2">{{ $sp->codeSpecialite }}-{{ $sp->libelleSpecialite }}</td>
                        </tr>
                    @endif
                    @if($annee->id == $scol->anneeacademique_id)
                        <tr>
                            <td>{{ \Illuminate\Support\Str::upper($scol->descriptionScolarite) }}</td>
                            <td>{{ $scol->montantScolarite }} FCFA</td>
                        </tr>
                    @endif
                    @if($i==count($sp->scolarite)-1)
                        <tr>
                            <td  id="entete" style="background-color: rgba(180,183,171,0.69)">Total</td>
                            <td>{{ $sp->scolarite->sum("montantScolarite") }} FCFA</td>
                        </tr>
                    @endif
                @endforeach
            @endforeach
        </table>
    @else
        <table class="table" border="box" rules="all" width="100%" align="center">
            <tr>
                <td>Aucune entré touvé</td>
            </tr>
        </table>
    @endif
</main>
</body>
</html>