<!DOCTYPE html>
<html>
<head>
    <title>Generated by ISSAT - Fiche de description </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        @page {
            margin: 10px 30px;
        }
        .page-break {
            page-break-after: always;
        }

        th, td{
            font-size: 12px;
        }

        h4{
            padding: 0px;
            margin: 0px;
        }

        h6{
            margin: 2px;
            padding: 2px;
        }

        h6 span{
            font-size: 8px;
            color: #ffaa04;
        }

        #body td{
            font-size: 12px;
        }

        .tr-title{
            padding: 10px;
            border-bottom: 1px solid #000000;
            background: ##e1e3e1;
            text-align: center;
            color: #000000;
            font-weight: bold;
        }
        input[type=checkbox] { display: inline; }
        input[type=checkbox]:before { font-family: DejaVu Sans; }
        #watermark {
            position: fixed;
            bottom:   2cm;
            width:    20cm;
            height:   20cm;
            z-index:  -1000;
            opacity: 0.2;
        }

    </style>
</head>
<body>
<div id="watermark">
    <img src="{{ asset("") }}assets/images/logo/issat.png" height="100%" width="100%" />
</div>
@if(isset($data["data"]->cycle))
    <header>
        @include("pdf.entete")
    </header>
    <main id="body">
        <table class="table"  border="box" rules="all" width="100%" align="center">
            <tr class="tr-title">
                <td colspan="4">
                    <h4>Cycle : {{ $data["data"]->dossier->cycle }} / Niveau: {{ $data["data"]->dossier->level->numeroLevel }}</h4>
                    <h3 style="height: 1px">IDENTIFICATION DU CANDIDAT/ CANDIDAT’S IDENTIFICATION</h3>
                </td>
            </tr>


            <tr class="text-left">
                <td rowspan="4" width="32%" style="height: 200px; padding: 0; margin: 0">
                    <img src="{{ !empty($data["data"]->etudiant->avatar)? asset("").$data["data"]->etudiant->avatar : 'assets/images/avatars/avatar.png' }}" alt="" class="img-fluid" style="width: 120px; height: 120px">
                </td>
                <td colspan="3">
                    <i>Nom et Prenoms / First name and surname</i>
                    <h4>{{ $data["data"]->etudiant->lastname }} {{ $data["data"]->etudiant->firstname }}</h4>
                </td>
            </tr>
            <tr class="text-left">
                <td>
                    <i>Né (e) le / Born on the: </i>
                    <h4>{{ date('d/m/Y', strtotime($data["data"]->etudiant->birthday)) }}</h4>
                </td>
                <td>
                    <i>A/ at:</i>
                    <h4>{{ $data["data"]->etudiant->birthplace }}</h4>
                </td>
                <td>
                    <i>Region:</i>
                    <h4>{{ $data["data"]->etudiant->region }}</h4>
                </td>
            </tr>
            <tr class="text-left">
                <td>
                    <i>Nationalité/ Nationality : </i>
                    <h4>{{ $data["data"]->etudiant->nationality }}</h4>
                </td>
                <td colspan="2">
                    <i>Langues officielles/ Officials languages : </i>
                    <h4>{{ $data["data"]->etudiant->language }}</h4>
                </td>
            </tr>
            <tr class="text-left">
                <td>
                    <i>Télephone/ Phone number : </i>
                    <h4>{{ $data["data"]->etudiant->phonenumber }}</h4>
                </td>
                <td colspan="2">
                    <i>e-mail: </i>
                    <h4>{{ $data["data"]->etudiant->email }}</h4>
                </td>
            </tr>



            <tr class="tr-title">
                <td colspan="4"><h3>PROFIL SCOLAIRE/ ACADEMIC PROFIL</h3></td>
            </tr>
            <tr class="text-left">
                <td colspan="4">
                    <i>Choix de formation :  </i>
                    <h5 style="padding-left: 20px; padding-top: -60px">
                        <ol >
                            <li><input type="checkbox" checked="{{ $data["data"]->choice[0]->etat==1? "checked" : "" }}" />{{ $data["data"]->choice[0]->specialite->libelleSpecialite }};</li>
                            <li><input type="checkbox" checked="{{ $data["data"]->choice[1]->etat==1? "checked" : "" }}" />{{ $data["data"]->choice[1]->specialite->libelleSpecialite }};</li>
                            <li><input type="checkbox" checked="{{ $data["data"]->choice[2]->etat==1? "checked" : "" }}" />{{ $data["data"]->choice[2]->specialite->libelleSpecialite }};</li>
                        </ol>
                    </h5>
                </td>
            </tr>
            <tr class="text-left">
                <td colspan="2">
                    <i>Diplôme d’admission/ Admission’s diploma  </i>
                    <h4>{{ $data["data"]->parcour->admissiondiploma }}</h4>
                </td>
                <td>
                    <i>Serie/ option :</i>
                    <h4>{{ $data["data"]->parcour->option }}</h4>
                </td>
                <td>
                    <i>Année d’obtention/ School year :</i>
                    <h4>{{ $data["data"]->parcour->schoolyear }}</h4>
                </td>
            </tr>
            <tr class="text-left">
                <td colspan="2">
                    <i>Pays d’obtention/ Diploma’s country  :  </i>
                    <h4>{{ $data["data"]->parcour->diplomacountry }}</h4>
                </td>
                <td colspan="2">
                    <i>Etablissement/ School attended  : </i>
                    <h4>{{ $data["data"]->parcour->schoolattended }}</h4>
                </td>
            </tr>



            <tr class="tr-title">
                <td colspan="4"><h3>INFORMATIONS COMPLEMENTAIRES/ FURTHER INFORMATION</h3></td>
            </tr>
            <tr class="text-left">
                <td><label>Noms du père/ Name of father  : </label></td>
                <td colspan="3"><label>{{ $data["data"]->etudiant->parent->fathername }}</label></td>
            </tr>

            <tr class="text-left">
                <td><label>Profession : </label></td>
                <td><label>{{ $data["data"]->etudiant->parent->fatherprofession }}</label></td>
                <td><label>Contact:</label></td>
                <td><label>{{ $data["data"]->etudiant->parent->fathercontact }}</label></td>
            </tr>
            <tr class="text-left">
                <td><label>Noms de la mère/ Name of mother  : </label></td>
                <td colspan="3"><label>{{ $data["data"]->etudiant->parent->mothername }}</label></td>
            </tr>
            <tr class="text-left">
                <td><label>Profession : </label></td>
                <td><label>{{ $data["data"]->etudiant->parent->motherprofession }}</label></td>
                <td><label>Contact :</label></td>
                <td><label>{{ $data["data"]->etudiant->parent->mothercontact }}</label></td>
            </tr>
            <tr class="text-left">
                <td><label>Personne à contacter en cas d’urgence : </label></td>
                <td><label>{{ $data["data"]->etudiant->parent->emergencyname }}</label></td>
                <td><label>Contact :</label></td>
                <td><label>{{ $data["data"]->etudiant->parent->emergencycontact }}</label></td>
            </tr>
            <tr class="text-left">
                <td><label>Sport préfére : </label></td>
                <td><label>{{ $data["data"]->etudiant->sport }}</label></td>
                <td><label>Loisir :</label></td>
                <td><label>{{ $data["data"]->etudiant->leisure }}</label></td>
            </tr>


            <tr class="tr-title">
                <td colspan="4"><h3>ANTECEDANT MEDICAUX/ MEDICAL HISTORY</h3></td>
            </tr>
            <tr class="text-left">
                <td><label>Pathologie /Pathology  : </label></td>
                <td><label>Date de la derniere consultation /<br> Date of last consultation</label></td>
                <td colspan="2"><label>Observation /<br> Observation</label></td>
            </tr>
            @foreach($data["data"]->etudiant->antecedants as $a)
                <tr class="text-left">
                    <td><label>{{ $a->maladie }}</label></td>
                    <td><label>{{ $a->dateconsultation }}</label></td>
                    <td colspan="2"><label>{{ $a->etat }}</label></td>
                </tr>
            @endforeach

            <tr class="text-left">
                <td colspan="4" class="text-right " style="padding:50px; border: 1px solid #ffffff "><h4><span style="border-bottom:1px dotted #000000; float: right">Date et visa de l'administration</span></h4></td>
            </tr>

        </table>
    </main>
@else

    @foreach($data["data"] as $i=>$et)
        <header>
            @include("pdf.entete")
        </header>
        <main id="body">
            <table class="table" border="box" rules="all" width="100%" align="center">
                <tr class="tr-title">
                    <td colspan="5">
                        <h2>ANNEE ACADEMIQUE {{ $et->anneacademique->numeroAnnee }}-{{ intval($et->anneacademique->numeroAnnee)+1 }}</h2>
                        <h2>Cycle : {{ isset($et->dossier->cycle)?$et->dossier->cycle->codeCycle : "inconnu" }} / Niveau: {{ $et->level->numeroLevel }}</h2>
                    </td>
                </tr>
            </table>
            <br>
            <table class="table" border="box" rules="all" width="100%" align="center">
                <tr class="tr-title">
                    <td colspan="5">
                        <h3 style="height: 1px">IDENTIFICATION DU CANDIDAT/ CANDIDAT’S IDENTIFICATION</h3>
                    </td>
                </tr>
                <tr class="text-left">
                    <td rowspan="4" colspan="1" width="32%" style="padding: 0; margin: 0;">
                        <img src="{{ (isset($et) && !empty($et->dossier->etudiant->avatar))? asset("").$et->dossier->etudiant->avatar : "assets/images/avatars/avatar.png" }}" style="width: 200px; height: 200px;  margin: 0; padding: 0; padding-left:20px;" alt="">
                    </td>
                    <td colspan="4">
                        <i>Nom et Prenoms / First name and surname</i>
                        <h4>{{ $et->dossier->etudiant->lastname }} {{ $et->dossier->etudiant->firstname }}</h4>
                    </td>
                </tr>
                <tr class="text-left">
                    <td>
                        <i>Né (e) le / Born on the: </i>
                        <h4>{{ date('d/m/Y', strtotime($et->dossier->etudiant->birthday)) }}</h4>
                    </td>
                    <td>
                        <i>A/ at:</i>
                        <h4>{{ $et->dossier->etudiant->birthplace }}</h4>
                    </td>
                    <td colspan="2">
                        <i>Region:</i>
                        <h4>{{ $et->dossier->etudiant->region }}</h4>
                    </td>
                </tr>
                <tr class="text-left">
                    <td colspan="1">
                        <i>Nationalité/ Nationality : </i>
                        <h4>{{ $et->dossier->etudiant->nationality }}</h4>
                    </td>
                    <td colspan="3">
                        <i>Langues officielles/ Officials languages : </i>
                        <h4>{{ $et->dossier->etudiant->language }}</h4>
                    </td>
                </tr>
                <tr class="text-left">
                    <td colspan="1">
                        <i>Télephone/ Phone number : </i>
                        <h4>{{ $et->dossier->etudiant->phonenumber }}</h4>
                    </td>
                    <td colspan="3">
                        <i>e-mail: </i>
                        <h4>{{ $et->dossier->etudiant->email }}</h4>
                    </td>
                </tr>



                <tr class="tr-title">
                    <td colspan="5"><h3>PROFIL SCOLAIRE/ ACADEMIC PROFIL</h3></td>
                </tr>
                <tr class="text-left">
                    <td colspan="5">
                        <i>Choix de formation :  </i>
                        <h5 style="padding-left: 20px; padding-top: -60px; ">
                            <ol type="none">
                                <li style="{{ $et->choice[0]->etat==1? "background: #4266f5; color:#ffffff;" : "" }}">{{ $et->choice[0]->specialite->codeSpecialite }} - {{ $et->choice[0]->specialite->libelleSpecialite }};</li>
                                <li style="{{ $et->choice[1]->etat==1? "background: #4266f5; color:#ffffff;" : "" }}">{{ $et->choice[1]->specialite->codeSpecialite }} - {{ $et->choice[1]->specialite->libelleSpecialite }};</li>
                                <li style="{{ $et->choice[2]->etat==1? "background: #4266f5; color:#ffffff;" : "" }}">{{ $et->choice[2]->specialite->codeSpecialite }} - {{ $et->choice[2]->specialite->libelleSpecialite }};</li>
                            </ol>
                        </h5>
                    </td>
                </tr>

                <tr>
                    <td colspan="5">
                        <table width="100%" border="box" rules="all">
                            <thead class="tr-title">
                                <th><label>Diplôme d’admission/ Admission’s diploma  </label></th>
                                <th><label>Serie/ option </label></th>
                                <th><label>Année d’obtention/ School year </label></th>
                                <th><label>Pays d’obtention/ Diploma’s country</label></th>
                                <th><label>Etablissement/ School attended  </label></th>
                            </thead>
                            <tbody>
                            @foreach($et->dossier->parcours as $p)
                                <tr class="text-left">
                                    <td colspan="1"><label>{{ $p->admissiondiploma }}</label></td>
                                    <td colspan="1"><label>{{ $p->option }}</label></td>
                                    <td colspan="1"><label>{{ $p->schoolyear }}</label></td>
                                    <td colspan="1"><label>{{ $p->diplomacountry }}</label></td>
                                    <td colspan="1"><label>{{ $p->schoolattended }}</label></td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </td>
                </tr>

                <tr class="tr-title">
                    <td colspan="5"><h3>INFORMATIONS COMPLEMENTAIRES/ FURTHER INFORMATION</h3></td>
                </tr>
                <tr class="text-left">
                    <td><label>Noms du père/ Name of father  : </label></td>
                    <td colspan="4"><label>{{ $et->dossier->etudiant->parents->fathername }}</label></td>
                </tr>

                <tr class="text-left">
                    <td><label>Profession : </label></td>
                    <td><label>{{ $et->dossier->etudiant->parents->fatherprofession }}</label></td>
                    <td><label>Contact:</label></td>
                    <td colspan="2"><label>{{ $et->dossier->etudiant->parents->fathercontact }}</label></td>
                </tr>
                <tr class="text-left">
                    <td><label>Noms de la mère/ Name of mother  : </label></td>
                    <td colspan="4"><label>{{ $et->dossier->etudiant->parents->mothername }}</label></td>
                </tr>
                <tr class="text-left">
                    <td><label>Profession : </label></td>
                    <td><label>{{ $et->dossier->etudiant->parents->motherprofession }}</label></td>
                    <td><label>Contact :</label></td>
                    <td colspan="2"><label>{{ $et->dossier->etudiant->parents->mothercontact }}</label></td>
                </tr>
                <tr class="text-left">
                    <td><label>Personne à contacter en cas d’urgence : </label></td>
                    <td><label>{{ $et->dossier->etudiant->parents->emergencyname }}</label></td>
                    <td><label>Contact :</label></td>
                    <td colspan="2"><label>{{ $et->dossier->etudiant->parents->emergencycontact }}</label></td>
                </tr>
                <tr class="text-left">
                    <td><label>Sport préfére : </label></td>
                    <td><label>{{ $et->dossier->etudiant->sport }}</label></td>
                    <td><label>Loisir :</label></td>
                    <td colspan="2"><label>{{ $et->dossier->etudiant->leisure }}</label></td>
                </tr>


                <tr class="tr-title">
                    <td colspan="5"><h3>ANTECEDANT MEDICAUX/ MEDICAL HISTORY</h3></td>
                </tr>
                <tr class="text-left">
                    <td><label>Pathologie /Pathology  : </label></td>
                    <td colspan="2"><label>Date de la derniere consultation /Date of last consultation</label></td>
                    <td colspan="2"><label>Observation / Observation</label></td>
                </tr>
                @foreach($et->dossier->etudiant->antecedants as $a)
                    <tr class="text-left">
                        <td><label>{{ $a->maladie }}</label></td>
                        <td colspan="2"><label>{{ $a->dateconsultation }}</label></td>
                        <td colspan="2"><label>{{ $a->etat }}</label></td>
                    </tr>
                @endforeach

                <tr class="text-left">
                    <td colspan="5" class="text-right " style="padding:50px; border: 1px solid #ffffff "><h4><span style="border-bottom:1px dotted #000000; float: right">Date et visa de l'administration</span></h4></td>
                </tr>

            </table>
        </main>

        @if($i<=count($data)-2)
            <div class="page-break"></div>
        @endif
    @endforeach
@endif
</body>
</html>