<!DOCTYPE html>
<html>
<head>
    <title>Generated by SCHOOLADMIN - Fiche de description </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        @page {
            margin: 10px 10px;
        }
        .page-break {
            page-break-after: always;
        }

        h4{
            padding: 0px;
            margin: 0px;
        }

        h6{
            margin: 2px;
            padding: 2px;
        }

        h6 span{
            font-size: 8px;
            color: #ffaa04;
        }

        #body td{
            font-size: 7px;
        }

        .tr-title{
            padding: 10px;
            border-bottom: 1px solid #000000;
            background: ##e1e3e1;
            text-align: center;
            color: #000000;
        }

        .td-result{
            background: rgb(221, 222, 216);
            text-align: center;
        }

        input[type=checkbox] { display: inline; }
        input[type=checkbox]:before { font-family: DejaVu Sans; }
        #watermark {
            position: fixed;

            /** Change image dimensions**/
            width:    20cm;
            /*height:   20cm;*/

            /** Your watermark should be behind every content**/
            z-index:  -1000;
            opacity: 0.2;
            left: 14%;
        }

        .longText{
            /*transform: rotate(-90deg);*/

            /*-webkit-transform: rotate(-90deg);*/

            /*!* Firefox *!*/
            /*-moz-transform: rotate(-90deg);*/

            /*!* IE *!*/
            /*-ms-transform: rotate(-90deg);*/

            /*!* Opera *!*/
            /*-o-transform: rotate(-90deg);*/

            /*!* Internet Explorer *!*/
            /*filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);*/
        }

        #body td, #body th{
            font-size: 7px;
            text-align: center;
        }

        #entete td, #entete th{
            font-size: 8px;
            text-align: center;
        }

        /*tbody td{*/
            /*font-size: 5px;*/
        /*}*/

        .bg-danger{
            background-color: rgba(255, 0, 0, 0.49);
        }
        .bg-success{
            background-color: rgba(1, 203, 114, 0.51);
        }

        #header{
            font-size: 14px;
        }


    </style>
</head>
<body>
<div id="watermark">
    <img src="{{ asset("") }}assets/images/logo/issat.png" height="100%" width="100%" />
</div>

<header>
    @include("pdf.entete-pv")
</header>
<hr style="background-color: #999999; border: 1px dashed #cccccc">
<main id="body">
    @foreach($semestres as $i=>$s)
        <h4 style="text-align: center;">SEMESTRE {{ $s->libelleSemestre }}</h4>
        @foreach($specialite as $sp)
            @if(count($sp->choice)>0)

                    @php
                        $headinscription = array();
                        $bodyinscription = array();
                        $allMoyenne = 0;
                        $maxMoyenne = 0;
                        $minMoyenne = 0;
                        $totalAll = 0;
                        $winners = 0;
                    @endphp


                    @foreach($sp->choice as $c)
                        @if($c->etat==1 && !in_array($sp, $headinscription))
                            <table class="table" border="box" rules="none" align="center" id="entete" style="width: 100%">
                                <tr>
                                    <td width="">
                                        <h3>{{ $sp->codeSpecialite }} = {{ $sp->libelleSpecialite }} </h3>

                                        @if(count($sp->ues)>0)
                                            @foreach($sp->ues as $ue)
                                                @if($ue->semestre->libelleSemestre==$s->libelleSemestre)
                                                    <b>{{ $ue->codeUE }} = {{ $ue->libelleUE }}</b> -
                                                    <i>
                                                    @foreach($ue->matiere as $m)
                                                        {{ $m->codeMatiere }} = {{ $m->libelleMatiere }},
                                                    @endforeach
                                                    </i>
                                                @endif
                                            @endforeach
                                        @endif

                                    </td>
                                </tr>
                            </table>
                            @php
                                array_push($headinscription, $sp)
                            @endphp
                        @endif
                    @endforeach

                    @foreach($sp->choice as $c)

                        @if($c->etat==1 && !in_array($sp, $bodyinscription))
                        <table class="table" border="box" rules="all" width="100%" align="center">
                            <thead class="tr-title">
                                <tr>
                                    <th style="border: none"></th>
                                    <th style="border: none"></th>
                                    <th style="border: none"></th>
                                    @foreach($sp->ues as $ue)
                                        @if($ue->semestre->libelleSemestre==$s->libelleSemestre)
                                            <th colspan="{{ (count($ue->matiere) * 3)+4 }}" ><span class="longText">{{ $ue->codeUE }}</span></th>
                                        @endif
                                    @endforeach
                                    <th colspan="4" rowspan="2">SYNTHESE GENERALE</th>
                                </tr>

                                <tr>
                                    <th style="border: none"></th>
                                    <th style="border: none"></th>
                                    <th style="border: none"></th>
                                    @foreach($sp->ues as $ue)
                                        @if($ue->semestre->libelleSemestre==$s->libelleSemestre)
                                            @foreach($ue->matiere as $m)
                                                <th colspan="3">{{ $m->codeMatiere }}</th>
                                            @endforeach
                                            <th colspan="4"><span class="longText">SYNTHESE UE {{ $ue->codeUE }}</span></th>
                                        @endif
                                    @endforeach
                                </tr>

                                <tr>
                                    <th width="2%">#</th>
                                    <th width="5%">MATRICULE</th>
                                    <th width="13%">NOM(S) & PRENOM(S)</th>
                                    @foreach($sp->ues as $ue)
                                        @if($ue->semestre->libelleSemestre==$s->libelleSemestre)
                                            @foreach($ue->matiere as $m)
                                                <th>CC</th>
                                                <th>EX</th>
                                                <th>MOY EC</th>
                                            @endforeach
                                            <th>MOY UE</th>
                                            <th>GRA</th>
                                            <th>CRE</th>
                                            <th>DEC</th>
                                        @endif
                                    @endforeach
                                    <th>MOY UE</th>
                                    <th>GRA</th>
                                    <th>CRE</th>
                                    <th>DEC</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php
                                    $count = 0;
                                    $moyenne = 0;
                                    array_push($bodyinscription, $sp)
                                @endphp

                                @foreach($sp->choice as $c)
                                    @if($c->etat==1)
                                        @php
                                            $moyenneFinale = 0;
                                            $creditFinale = 0;
                                            $nbFinale = 0;
                                        @endphp
                                        <tr>
                                            <td>{{ ++$count }}</td>
                                            <td>{{ $c->inscription->matricule }}</td>
                                            <td>{{ $c->inscription->etudiant->lastname }} {{ $c->inscription->etudiant->firstname }}</td>
                                            @foreach($sp->ues as $ue)
                                                @php
                                                    $moyenne = 0;
                                                    $notecc = 0;
                                                    $noteexam = 0;
                                                    $credits = 0;
                                                @endphp
                                                @if($ue->semestre->libelleSemestre==$s->libelleSemestre)
                                                @foreach($ue->matiere as $m)
                                                    @php
                                                        $cc = \App\Models\Note::where("matiere_id", "=", $m->id)
                                                        ->where("etudiant_id", "=", $c->inscription->etudiant_id)
                                                        ->where("semestre_id", "=", $s->id)
                                                        ->where("typeevaluation", "=", "cc")
                                                        ->first();


                                                        $exam = \App\Models\Note::where("matiere_id", "=", $m->id)
                                                        ->where("etudiant_id", "=", $c->inscription->etudiant_id)
                                                        ->where("semestre_id", "=", $s->id)
                                                        ->where("typeevaluation", "=", "normal")
                                                        ->first();

                                                        $notecc = !empty($cc)?  $cc->moyenne*bcdiv(30,100,3) : 0;
                                                        $noteexam = !empty($exam)?  $exam->moyenne*bcdiv(70,100,3) : 0;
                                                        $moyenne += bcdiv(($notecc+$noteexam),count($ue->matiere),3);

                                                        if ($notecc+$noteexam>=10){
                                                            $credits+= $m->creditMatiere;
                                                        }

                                                    @endphp

                                                    <td>{{ !empty($cc)? $cc->moyenne : "" }}</td>
                                                    <td>{{ !empty($exam)? $exam->moyenne : "" }}</td>
                                                    <td>{{ $notecc+$noteexam }}</td>

                                                @endforeach
                                                    <td class="td-result {{ $moyenne<10? "bg-danger" : ($moyenne>=12? "bg-success" : "") }}">{{ round($moyenne, 3) }}</td>
                                                    <td class="td-result {{ $moyenne<10? "bg-danger" : ($moyenne>=12? "bg-success" : "") }}">
                                                        @php
                                                            $moyenneFinale += $moyenne;
                                                            $nbFinale++;
                                                            if ($moyenne>=16){
                                                                echo "A";
                                                            }

                                                            if ($moyenne>=14 && $moyenne<16){
                                                                echo "B";
                                                            }

                                                            if ($moyenne>=12 && $moyenne<14){
                                                                echo "C";
                                                            }

                                                            if ($moyenne>=10 && $moyenne<12){
                                                                echo "D";
                                                            }

                                                            if ($moyenne>=8 && $moyenne<10){
                                                                echo "E";
                                                            }

                                                            if ($moyenne<8){
                                                                echo "F";
                                                            }
                                                        @endphp
                                                    </td>
                                                    <td class="td-result {{ $moyenne<10? "bg-danger" : ($moyenne>=12? "bg-success" : "") }}">
                                                        @php
                                                            echo $credits;
                                                            $creditFinale += $credits;
                                                        @endphp
                                                    </td>
                                                    <td class="td-result {{ $moyenne<10? "bg-danger" : ($moyenne>=12? "bg-success" : "") }}">
                                                        @php
                                                            if ($moyenne>=10){
                                                                echo "CA";
                                                            }
                                                            if ($moyenne>=9 && $moyenne<10 ){
                                                                echo "CANT";
                                                            }
                                                            if ($moyenne>=0 && $moyenne<9 ){
                                                                echo "EL";
                                                            }
                                                        @endphp
                                                    </td>
                                                @endif
                                            @endforeach

                                            <td class="td-result {{ round($moyenneFinale/$nbFinale, 3)<10? "bg-danger" : (round($moyenneFinale/$nbFinale, 3)>=12? "bg-success" : "") }}">{{ round($moyenneFinale/$nbFinale, 3) }}</td>
                                            <td class="td-result {{ round($moyenneFinale/$nbFinale, 3)<10? "bg-danger" : (round($moyenneFinale/$nbFinale, 3)>=12? "bg-success" : "") }}">
                                                @php
                                                    if (round($moyenneFinale/$nbFinale, 3)>=18){
                                                        echo "A+";
                                                    }

                                                    if (round($moyenneFinale/$nbFinale, 3)>=16 && round($moyenneFinale/$nbFinale, 3)<18){
                                                        echo "A";
                                                    }

                                                    if (round($moyenneFinale/$nbFinale, 3)>=14 && round($moyenneFinale/$nbFinale, 3)<16){
                                                        echo "B+";
                                                    }

                                                    if (round($moyenneFinale/$nbFinale, 3)>=13 && round($moyenneFinale/$nbFinale, 3)<14){
                                                        echo "B";
                                                    }

                                                    if (round($moyenneFinale/$nbFinale, 3)>=12 && round($moyenneFinale/$nbFinale, 3)<13){
                                                        echo "B-";
                                                    }

                                                    if (round($moyenneFinale/$nbFinale, 3)>=11 && round($moyenneFinale/$nbFinale, 3)<12){
                                                        echo "C+";
                                                    }

                                                    if (round($moyenneFinale/$nbFinale, 3)>=10 && round($moyenneFinale/$nbFinale, 3)<11){
                                                        echo "C";
                                                    }

                                                    if (round($moyenneFinale/$nbFinale, 3)>=9 && round($moyenneFinale/$nbFinale, 3)<10){
                                                        echo "C-";
                                                    }

                                                    if (round($moyenneFinale/$nbFinale, 3)>=8 && round($moyenneFinale/$nbFinale, 3)<9){
                                                        echo "D";
                                                    }

                                                    if (round($moyenneFinale/$nbFinale, 3)>=6 && round($moyenneFinale/$nbFinale, 3)<8){
                                                        echo "E";
                                                    }

                                                    if (round($moyenneFinale/$nbFinale, 3)<6){
                                                        echo "F";
                                                    }
                                                @endphp
                                            </td>
                                            <td class="td-result {{ round($moyenneFinale/$nbFinale, 3)<10? "bg-danger" : (round($moyenneFinale/$nbFinale, 3)>=12? "bg-success" : "") }}">{{ $creditFinale }}</td>
                                            <td class="td-result {{ round($moyenneFinale/$nbFinale, 3)<10? "bg-danger" : (round($moyenneFinale/$nbFinale, 3)>=12? "bg-success" : "") }}">
                                                @php
                                                    if (round($moyenneFinale/$nbFinale, 3)>=10){
                                                        echo "CA";
                                                    }
                                                    if (round($moyenneFinale/$nbFinale, 3)>=9 && round($moyenneFinale/$nbFinale, 3)<10 ){
                                                        echo "CANT";
                                                    }
                                                    if (round($moyenneFinale/$nbFinale, 3)>=0 && round($moyenneFinale/$nbFinale, 3)<9 ){
                                                        echo "EL";
                                                    }
                                                @endphp
                                            </td>
                                        </tr>
                                        @php
                                            $totalAll++;
                                            round($moyenneFinale/$nbFinale, 3)>=10? $winners++ : "";
                                            $allMoyenne += round($moyenneFinale/$nbFinale, 3);
                                            $maxMoyenne = (round($moyenneFinale/$nbFinale, 3)>$maxMoyenne)? round($moyenneFinale/$nbFinale, 3) : $maxMoyenne;
                                            $minMoyenne = (round($moyenneFinale/$nbFinale, 3)<$minMoyenne)? round($moyenneFinale/$nbFinale, 3) : $minMoyenne;;
                                        @endphp
                                    @endif
                                @endforeach
                            </tbody>
                        </table>

                        @endif
                    @endforeach
                <p class="paragraphe" style="text-align:center">Décision:    CA=Capitalisé; CANT=Capitalisé Non transférable; NC=Non Capitalisé; EL=Eliminé</p>
                <p class="paragraphe" style="text-align:center">
                    Grade et notes sur 20:
                    A+ [18-20];  A [16-18[;
                    B+ [14-16[;  B [13-14[;  B- [12-13[;
                    C+ [11-12[;  C [10-11[;  C- [11-10[;
                    D [08-09[;  E [06-08[;  F [00-06[;
                </p>
                <br>
                <br>
                <table class="table" border="box" rules="all" width="50%" align="center">
                    <tbody >
                        <tr>
                            <td>MOYENNE GENERALE</td>
                            <td>{{ round($allMoyenne/$totalAll, 3) }}</td>
                        </tr>
                        <tr>
                            <td>TAUX DE REUSSITE</td>
                            <td>{{ ($winners/$totalAll)*100 }}%</td>
                        </tr>
                        <tr>
                            <td>MOYENNE MAXIMALE</td>
                            <td>{{ $maxMoyenne }}</td>
                        </tr>
                        <tr>
                            <td>MOYENNE MINIMALE</td>
                            <td>{{ $minMoyenne }}</td>
                        </tr>
                    </tbody>
                </table>
            @endif
        @endforeach
        @if($i<=count($semestres)-2)
        <div class="page-break"></div>
        @endif
    @endforeach
</main>
</body>
</html>