<!DOCTYPE html>
<html>
<head>
    <title>Generated by ISSAT - Fiche de description </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        @page {
            margin: 5px 5px;
        }
        .page-break {
            page-break-after: always;
        }

        h4{
            padding: 0px;
            margin: 0px;
        }

        h6{
            margin: 2px;
            padding: 2px;
        }

        h6 span{
            font-size: 16px;
            color: #ffaa04;
        }

        #body td{
            font-size: 16px;
            text-align:center;
        }

        .tr-title{
            padding: 10px;
            /*border-bottom: 1px solid #000000;*/
            background: #ffe200;
            text-align: center;
        }

        .td-result{
            background: rgb(221, 222, 216);
            text-align: center;
        }

        input[type=checkbox] { display: inline; }
        input[type=checkbox]:before { font-family: DejaVu Sans; }
        #watermark {
            position: fixed;

            /** Change image dimensions**/
            /*width:    20cm;*/
            /*height:   20cm;*/

            /** Your watermark should be behind every content**/
            z-index:  -1000;
            opacity: 0.2;
            left: 30%;
        }

        .longText{
            /*transform: rotate(-90deg);*/

            /*-webkit-transform: rotate(-90deg);*/

            /*!* Firefox *!*/
            /*-moz-transform: rotate(-90deg);*/

            /*!* IE *!*/
            /*-ms-transform: rotate(-90deg);*/

            /*!* Opera *!*/
            /*-o-transform: rotate(-90deg);*/

            /*!* Internet Explorer *!*/
            /*filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);*/
        }

        #body td, #body th{
            font-size: 16px;
            text-align: center;
            height: 30px;
            font-weight: bold;
            text-transform: uppercase;
        }

        #entete td, #entete th{
            font-size: 16px;
            text-align: center;
        }

        /*tbody td{*/
            /*font-size: 5px;*/
        /*}*/

        .bg-danger{
            background-color: rgba(255, 0, 0, 0.49);
        }
        .bg-success{
            background-color: rgba(1, 203, 114, 0.51);
        }

        #header{
            font-size: 16px;
        }

        .borderStrong{
            border:2px solid #000000;
        }


    </style>
</head>

<body>
    <div id="watermark">
        <img src="assets/images/logo/issat.png" height="100%" width="100%" />
    </div>

    <hr style="background-color: #999999; border: 1px dashed #cccccc">

    <main id="body">
        @php
            $allCount = count(\Illuminate\Support\Facades\DB::table("notes")->where("inscription_id", "=", $pvs[0]->inscription_id)->get());
            $totalUE = 0;
            $totalUEExist = 0;
            $totalMatiereExist = 0;
            $ueDone = array();
        @endphp


        @foreach($semestre as $sem)
            @php
                $count=0;
                $moyennesTotale = array();
                $creditTotale = array();
                foreach ($pvs as $pv){
                    $creditTotale[$pv->inscription_id] = 0;
                    $moyennesTotale[$pv->inscription_id] = 0;
                }
            @endphp
            @foreach($pvs as $k=>$pv)
                @if($count==0)
                    @foreach($ues as $ue)
                        @if($ue->semestre_id==$sem->id)
                            @php
                                $totalUEExist ++;
                                $totalMatiereExist += count($ue->matiere);
                            @endphp
                        @endif
                    @endforeach
                    @break
                @endif
            @endforeach

            @for($i=0; $i<$totalUEExist; $i+=2)
                @include("pdf.entete-pv")
                @php
                    $count=0;
                    $uesArrays = array();
                @endphp
                <h1 width="100%" style="text-align: center">{{ $pvs[0]->codeSpecialite }} = {{ $pvs[0]->libelleSpecialite }}</h1>
                <h3 width="100%" style="text-align: center">SEMESTRE {{ $sem->libelleSemestre }}</h3>
                <table class="table" border="box" rules="all" width="100%" align="center">
                    @foreach($pvs as $k=>$pv)
                        @php
                            $totalNotes = 0;
                            $totalCredit = 0;
                            $countMatiere = 0;
                        @endphp

                        @if($count==0)
                            <tr class="tr-title">
                                <td style="border: none"></td>
                                <td style="border: none"></td>
                                <td style="border: none"></td>
                                @foreach($ues as $ue)
                                    @if($ue->semestre_id==$sem->id && !in_array($ue->id, $ueDone))
                                        @if(count($ue->matiere)>0 && $countMatiere<2)
                                            @php
                                                $countMatiere++;
                                                array_push($ueDone, $ue->id);
                                                array_push($uesArrays, $ue->id);
                                            @endphp
                                            <td colspan="{{  (count($ue->matiere)*3)+4 }}">({{ $ue->codeUE }})<br> {{ $ue->libelleUE }}</td>
                                        @else
                                            @php
                                                $countMatiere=0;
                                            @endphp
                                            @break
                                        @endif
                                    @endif
                                @endforeach

                                @if($i==$totalUEExist-1)
                                    <td colspan="4" rowspan="2"  class="borderStrong">SYNTHESE GENERALE</td>
                                @endif
                            </tr>
                            <tr class="tr-title">
                                <td style="border: none"></td>
                                <td style="border: none"></td>
                                <td style="border: none"></td>
                                @foreach($ues as $ue)
                                    @if($ue->semestre_id==$sem->id && in_array($ue->id, $uesArrays))
                                        @if(count($ue->matiere)>0 && $countMatiere<2)
                                            @php
                                                $countMatiere++;
                                                array_push($ueDone, $ue->id)
                                            @endphp
                                            @foreach($ue->matiere as $m)
                                                <td colspan="3">({{ $m->codeMatiere }})<br> {{ $m->libelleMatiere }}</td>
                                            @endforeach
                                            <td colspan="4"><span class="longText">SYNTHESE UE {{ $ue->codeUE }}</span></td>
                                        @else
                                            @php
                                                $countMatiere=0;
                                            @endphp
                                            @break
                                        @endif

                                    @endif
                                @endforeach
                            </tr>


                            <tr class="tr-title">
                                <td>#</td>
                                <td>MATRICULE</td>
                                <td>NOM(S) & PRENOM(S)</td>
                                @foreach($ues as $ue)
                                    @if($ue->semestre_id==$sem->id &&  in_array($ue->id, $uesArrays))
                                        @if(count($ue->matiere)>0 )
                                            @foreach($ue->matiere as $m)
                                                <td>CC</td>
                                                <td>EX</td>
                                                <td>MOY</td>
                                            @endforeach
                                            <td>MOY UE</td>
                                            <td>GRA</td>
                                            <td>CRE</td>
                                            <td>DEC</td>
                                        @endif
                                    @endif
                                @endforeach

                                @if($i==$totalUEExist-1)
                                    <td class="borderStrong">MOY UE</td>
                                    <td class="borderStrong">GRA</td>
                                    <td class="borderStrong">CRE</td>
                                    <td class="borderStrong">DEC</td>
                                @endif
                            </tr>

                            <tr>
                                <td>{{ ++$count }}</td>
                                <td>{{ $pv->matriculeDossier }}</td>
                                <td>{{ \Illuminate\Support\Str::upper($pv->lastname) }} {{ \Illuminate\Support\Str::upper($pv->firstname) }}</td>
                                @foreach($ues as $ue)
                                    @if($ue->semestre_id==$sem->id && in_array($ue->id, $uesArrays))
                                        @if(count($ue->matiere)>0)
                                            @php
                                                $countMatiere++;
                                                $moyenneUE = 0;
                                                $creditUE = 0;
                                            @endphp
                                            @foreach($ue->matiere as $m)
                                                @php
                                                    $notecc = \App\Models\Note::where("inscription_id", "=", $pv->inscription_id)
                                                            ->where("semestre_id", "=", $sem->id)
                                                            ->where("matiere_id", "=", $m->id)
                                                            ->where("typeevaluation", "=", "cc")->first();
                                                            echo json_encode($notecc);

                                                    $notenormal = \App\Models\Note::where("inscription_id", "=", $pv->inscription_id)
                                                            ->where("semestre_id", "=", $sem->id)
                                                            ->where("matiere_id", "=", $m->id)
                                                            ->where("typeevaluation", "=", "normal")->first();

                                                    $cc = !empty($notecc)? $notecc->moyenne*0.3 : 0;
                                                    $normal = !empty($notenormal)? $notenormal->moyenne*0.7 : 0;
                                                    $moyenne = $cc+$normal;
                                                    $moyenneUE += round($moyenne/count($ue->matiere), 3);
                                                    if($moyenne>=10){
                                                        $creditUE += $m->creditMatiere;
                                                    }


                                                    $moyennesTotale[$pv->inscription_id] += $moyenne;

                                                @endphp
                                                <td>{{ round($cc/0.3, 3) }}</td>
                                                <td>{{ round($normal/0.7, 3) }}</td>
                                                <td>{{ $moyenne }}</td>
                                            @endforeach
                                            <td class="{{ $moyenneUE<10? "bg-danger" : ($moyenneUE>=12? "bg-success" : "") }}">{{ $moyenneUE }}</td>
                                            <td class="{{ $moyenneUE<10? "bg-danger" : ($moyenneUE>=12? "bg-success" : "") }}">
                                                @php

                                                    if ($moyenneUE>=16){
                                                        echo "A";
                                                    }

                                                    if ($moyenneUE>=14 && $moyenneUE<16){
                                                        echo "B";
                                                    }

                                                    if ($moyenneUE>=12 && $moyenneUE<14){
                                                        echo "C";
                                                    }

                                                    if ($moyenneUE>=10 && $moyenneUE<12){
                                                        echo "D";
                                                    }

                                                    if ($moyenneUE>=8 && $moyenneUE<10){
                                                        echo "E";
                                                    }

                                                    if ($moyenneUE<8){
                                                        echo "F";
                                                    }
                                                    $creditTotale[$pv->inscription_id] += $creditUE;
                                                @endphp
                                            </td>
                                            <td class="{{ $moyenneUE<10? "bg-danger" : ($moyenneUE>=12? "bg-success" : "") }}">{{ $creditUE }}</td>
                                            <td class="{{ $moyenneUE<10? "bg-danger" : ($moyenneUE>=12? "bg-success" : "") }}">
                                                @php
                                                    if ($moyenneUE>=10){
                                                        echo "CA";
                                                    }
                                                    if ($moyenneUE>=9 && $moyenneUE<10 ){
                                                        echo "CANT";
                                                    }
                                                    if ($moyenneUE>=0 && $moyenneUE<9 ){
                                                        echo "EL";
                                                    }
                                                @endphp
                                            </td>
                                        @else
                                            @php
                                                $countMatiere=0;
                                            @endphp
                                            @break
                                        @endif
                                    @endif
                                @endforeach

                                {{--@if($i==$totalUEExist-1)--}}
                                    {{--@php--}}
                                        {{--$moyenneFinaleGenerale = round($moyennesTotale[$pv->inscription_id]/$totalMatiereExist, 3);--}}
                                    {{--@endphp--}}
                                    {{--<td class="borderStrong {{ $moyenneFinaleGenerale<10? "bg-danger" : ($moyenneFinaleGenerale>=12? "bg-success" : "") }}">{{ $moyenneFinaleGenerale }}</td>--}}
                                    {{--<td class="borderStrong {{ $moyenneFinaleGenerale<10? "bg-danger" : ($moyenneFinaleGenerale>=12? "bg-success" : "") }}">--}}
                                        {{--@php--}}
                                            {{--if ($moyenneFinaleGenerale>=16){--}}
                                                {{--echo "A";--}}
                                            {{--}--}}

                                            {{--if ($moyenneFinaleGenerale>=14 && $moyenneFinaleGenerale<16){--}}
                                                {{--echo "B";--}}
                                            {{--}--}}

                                            {{--if ($moyenneFinaleGenerale>=12 && $moyenneFinaleGenerale<14){--}}
                                                {{--echo "C";--}}
                                            {{--}--}}

                                            {{--if ($moyenneFinaleGenerale>=10 && $moyenneFinaleGenerale<12){--}}
                                                {{--echo "D";--}}
                                            {{--}--}}

                                            {{--if ($moyenneFinaleGenerale>=8 && $moyenneFinaleGenerale<10){--}}
                                                {{--echo "E";--}}
                                            {{--}--}}

                                            {{--if ($moyenneFinaleGenerale<8){--}}
                                                {{--echo "F";--}}
                                            {{--}--}}
                                        {{--@endphp--}}
                                    {{--</td>--}}
                                    {{--<td class="borderStrong {{ $moyenneFinaleGenerale<10? "bg-danger" : ($moyenneFinaleGenerale>=12? "bg-success" : "") }}">{{ $creditTotale[$pv->inscription_id] }}</td>--}}
                                    {{--<td class="borderStrong {{ $moyenneFinaleGenerale<10? "bg-danger" : ($moyenneFinaleGenerale>=12? "bg-success" : "") }}">--}}
                                        {{--@php--}}
                                            {{--if ($moyenneFinaleGenerale>=10){--}}
                                                {{--echo "CA";--}}
                                            {{--}--}}
                                            {{--if ($moyenneFinaleGenerale>=9 && $moyenneFinaleGenerale<10 ){--}}
                                                {{--echo "CANT";--}}
                                            {{--}--}}
                                            {{--if ($moyenneFinaleGenerale>=0 && $moyenneFinaleGenerale<9 ){--}}
                                                {{--echo "EL";--}}
                                            {{--}--}}
                                        {{--@endphp--}}
                                    {{--</td>--}}
                                {{--@endif--}}
                            </tr>
                        @else
                            <tr>
                                <td>{{ ++$count }}</td>
                                <td>{{ $pv->matriculeDossier }}</td>
                                <td>{{ \Illuminate\Support\Str::upper($pv->lastname) }} {{ \Illuminate\Support\Str::upper($pv->firstname) }}</td>
                                {{--@foreach($ues as $ue)--}}
                                    {{--@if($ue->semestre_id==$sem->id && in_array($ue->id, $uesArrays))--}}
                                        {{--@if(count($ue->matiere)>0)--}}
                                            {{--@php--}}
                                                {{--$moyenneUE = 0;--}}
                                                {{--$creditUE = 0;--}}
                                            {{--@endphp--}}
                                            {{--@foreach($ue->matiere as $m)--}}
                                                {{--@php--}}
                                                    {{--$notecc = \App\Models\Note::where("inscription_id", "=", $pv->inscription_id)--}}
                                                            {{--->where("semestre_id", "=", $sem->id)--}}
                                                            {{--->where("matiere_id", "=", $m->id)--}}
                                                            {{--->where("typeevaluation", "=", "cc")->first();--}}

                                                    {{--$notenormal = \App\Models\Note::where("inscription_id", "=", $pv->inscription_id)--}}
                                                            {{--->where("semestre_id", "=", $sem->id)--}}
                                                            {{--->where("matiere_id", "=", $m->id)--}}
                                                            {{--->where("typeevaluation", "=", "normal")->first();--}}

                                                    {{--$cc = !empty($notecc)? $notecc->moyenne*0.3 : 0;--}}
                                                    {{--$normal = !empty($notenormal)? $notenormal->moyenne*0.7 : 0;--}}
                                                    {{--$moyenne = $cc+$normal;--}}
                                                    {{--$moyenneUE += round($moyenne/count($ue->matiere), 3);--}}
                                                    {{--if($moyenne>=10){--}}
                                                        {{--$creditUE += $m->creditMatiere;--}}
                                                    {{--}--}}

                                                    {{--$moyennesTotale[$pv->inscription_id] += $moyenne;--}}

                                                {{--@endphp--}}
                                                {{--<td>{{ round($cc/0.3, 3) }}</td>--}}
                                                {{--<td>{{ round($normal/0.7, 3) }}</td>--}}
                                                {{--<td>{{ $moyenne }}</td>--}}
                                            {{--@endforeach--}}
                                            {{--<td class="{{ $moyenneUE<10? "bg-danger" : ($moyenneUE>=12? "bg-success" : "") }}">{{ $moyenneUE }}</td>--}}
                                            {{--<td class="{{ $moyenneUE<10? "bg-danger" : ($moyenneUE>=12? "bg-success" : "") }}">--}}
                                                {{--@php--}}

                                                    {{--if ($moyenneUE>=16){--}}
                                                        {{--echo "A";--}}
                                                    {{--}--}}

                                                    {{--if ($moyenneUE>=14 && $moyenneUE<16){--}}
                                                        {{--echo "B";--}}
                                                    {{--}--}}

                                                    {{--if ($moyenneUE>=12 && $moyenneUE<14){--}}
                                                        {{--echo "C";--}}
                                                    {{--}--}}

                                                    {{--if ($moyenneUE>=10 && $moyenneUE<12){--}}
                                                        {{--echo "D";--}}
                                                    {{--}--}}

                                                    {{--if ($moyenneUE>=8 && $moyenneUE<10){--}}
                                                        {{--echo "E";--}}
                                                    {{--}--}}

                                                    {{--if ($moyenneUE<8){--}}
                                                        {{--echo "F";--}}
                                                    {{--}--}}

                                                    {{--$creditTotale[$pv->inscription_id] += $creditUE;--}}

                                                {{--@endphp--}}
                                            {{--</td>--}}
                                            {{--<td class="{{ $moyenneUE<10? "bg-danger" : ($moyenneUE>=12? "bg-success" : "") }}">{{ $creditUE }}</td>--}}
                                            {{--<td class="{{ $moyenneUE<10? "bg-danger" : ($moyenneUE>=12? "bg-success" : "") }}">--}}
                                                {{--@php--}}
                                                    {{--if ($moyenneUE>=10){--}}
                                                        {{--echo "CA";--}}
                                                    {{--}--}}
                                                    {{--if ($moyenneUE>=9 && $moyenneUE<10 ){--}}
                                                        {{--echo "CANT";--}}
                                                    {{--}--}}
                                                    {{--if ($moyenneUE>=0 && $moyenneUE<9 ){--}}
                                                        {{--echo "EL";--}}
                                                    {{--}--}}
                                                {{--@endphp--}}
                                            {{--</td>--}}
                                        {{--@endif--}}
                                    {{--@endif--}}
                                {{--@endforeach--}}

                                {{--@if($i==$totalUEExist-1)--}}
                                    {{--@php--}}
                                        {{--$moyenneFinaleGenerale = round($moyennesTotale[$pv->inscription_id]/$totalMatiereExist, 3);--}}
                                    {{--@endphp--}}
                                    {{--<td class="borderStrong {{ $moyenneFinaleGenerale<10? "bg-danger" : ($moyenneFinaleGenerale>=12? "bg-success" : "") }}">{{ $moyenneFinaleGenerale }}</td>--}}
                                    {{--<td class="borderStrong {{ $moyenneFinaleGenerale<10? "bg-danger" : ($moyenneFinaleGenerale>=12? "bg-success" : "") }}">--}}
                                        {{--@php--}}
                                            {{--if ($moyenneFinaleGenerale>=16){--}}
                                                {{--echo "A";--}}
                                            {{--}--}}

                                            {{--if ($moyenneFinaleGenerale>=14 && $moyenneFinaleGenerale<16){--}}
                                                {{--echo "B";--}}
                                            {{--}--}}

                                            {{--if ($moyenneFinaleGenerale>=12 && $moyenneFinaleGenerale<14){--}}
                                                {{--echo "C";--}}
                                            {{--}--}}

                                            {{--if ($moyenneFinaleGenerale>=10 && $moyenneFinaleGenerale<12){--}}
                                                {{--echo "D";--}}
                                            {{--}--}}

                                            {{--if ($moyenneFinaleGenerale>=8 && $moyenneFinaleGenerale<10){--}}
                                                {{--echo "E";--}}
                                            {{--}--}}

                                            {{--if ($moyenneFinaleGenerale<8){--}}
                                                {{--echo "F";--}}
                                            {{--}--}}
                                        {{--@endphp--}}
                                    {{--</td>--}}
                                    {{--<td class="borderStrong {{ $moyenneFinaleGenerale<10? "bg-danger" : ($moyenneFinaleGenerale>=12? "bg-success" : "") }}">{{ $creditTotale[$pv->inscription_id] }}</td>--}}
                                    {{--<td class="borderStrong {{ $moyenneFinaleGenerale<10? "bg-danger" : ($moyenneFinaleGenerale>=12? "bg-success" : "") }}">--}}
                                        {{--@php--}}
                                            {{--if ($moyenneFinaleGenerale>=10){--}}
                                                {{--echo "CA";--}}
                                            {{--}--}}
                                            {{--if ($moyenneFinaleGenerale>=9 && $moyenneFinaleGenerale<10 ){--}}
                                                {{--echo "CANT";--}}
                                            {{--}--}}
                                            {{--if ($moyenneFinaleGenerale>=0 && $moyenneFinaleGenerale<9 ){--}}
                                                {{--echo "EL";--}}
                                            {{--}--}}
                                        {{--@endphp--}}
                                    {{--</td>--}}
                                {{--@endif--}}
                            </tr>
                        @endif
                    @endforeach
                </table>
                <p class="paragraphe" style="text-align:center; font-size: 18px">Décision:    CA=Capitalisé; CANT=Capitalisé Non transférable; NC=Non Capitalisé; EL=Eliminé</p>
                <p class="paragraphe" style="text-align:center; font-size: 18px">
                    Grade et notes sur 20:
                    A+ [18-20];  A [16-18[;
                    B+ [14-16[;  B [13-14[;  B- [12-13[;
                    C+ [11-12[;  C [10-11[;  C- [11-10[;
                    D [08-09[;  E [06-08[;  F [00-06[;
                </p>
                <div class="page-break"></div>
            @endfor
        @endforeach

    </main>
</body>
</html>