<!DOCTYPE html>
<html>
<head>
    <title>Generated by ISSAT - Fiche de description </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        @page {
            margin: 5px 12px;
        }
        .page-break {
            page-break-after: always;
        }

        h1{
            font-size: 20px;
            padding: 0px;
            margin: 0px;
        }

        h2{
            font-size: 18px;
            padding: 0px;
            margin: 0px;
        }

        h4{
            padding: 0px;
            margin: 0px;
        }

        h6{
            margin: 2px;
            padding: 2px;
        }

        h6 span{
            font-size: 14px;
            color: #ffaa04;
        }

        #body td{
            font-size: 10px;
            text-align:center;
        }

        .tr-title, .tr-title th{
            /*border-bottom: 1px solid #000000;*/
            background: #ffe200;
            text-align: center;
            font-size: 8px!important;
        }

        .td-result{
            font-size: 8px!important;
        }

        input[type=checkbox] { display: inline; }
        input[type=checkbox]:before { font-family: DejaVu Sans; }
        #watermark {
            position: fixed;

            /** Change image dimensions**/
            /*width:    20cm;*/
            /*height:   20cm;*/

            /** Your watermark should be behind every content**/
            z-index:  -1000;
            opacity: 0.2;
            left: 15%;
        }

        #body td, #body th{
            font-size: 8px;
            text-align: center;
            text-transform: uppercase;
            font-weight: bold;
        }



        #header td, #entete td, #entete th{
            font-size: 12px;
            text-align: center;
        }

        /*tbody td{*/
        /*font-size: 5px;*/
        /*}*/

        .bg-danger{
            background-color: rgba(255, 0, 0, 0.49);
        }
        .bg-success{
            background-color: rgba(1, 203, 114, 0.51);
        }

        #header{
            font-size: 14px;
        }

        .borderStrong{
            border:2px solid #000000;
        }


    </style>
</head>
<body>
<div id="watermark">
    <img src="assets/images/logo/issat.png" style="width:500px; margin: 250px 300px"/>
</div>


<main id="body">

    @php
        $moyenneGeneral = 0;
        $moyenneMinimal = 0;
        $moyenneMaximal = 0;
        $totalCredit = 0;
    @endphp

    @foreach($semestre as $key1=>$sem)

        @include("pdf.entete-pv")
        <hr style="background-color: #d9d9d9; border: 1px dashed #cccccc">
        <h1 width="100%" style="text-align: center; padding:2px; maring: 2;">PROCES VERBAL DE NOTES DE FIN DE SEMESTRE {{ $sem->libelleSemestre }} ({{ $pvs[0]->numeroAnnee }}-{{ intval($pvs[0]->numeroAnnee)+1 }})</h1>
        <h2 width="100%" style="text-align: center; padding:2px; maring: 2;">{{ $pvs[0]->codeSpecialite }} = {{ $pvs[0]->libelleSpecialite }} (SEMESTRE {{ $sem->libelleSemestre }})</h2>

        <p style="font-size: 9px; ">
            @foreach($ues as $ue)
                @if($ue->semestre_id == $sem->id)
                    <span style="font-weight: bold">{{ $ue->codeUE }}={{ $ue->libelleUE }}</span>;&nbsp;
                    <br>
                    @foreach($ue->matiere as $m)
                        {{ $m->codeMatiere }}={{ $m->libelleMatiere }};&nbsp;
                    @endforeach
                    <br>
                @endif
            @endforeach
        </p>

        @php
            $countNotesMatiere = array();
            $countNotesUE = array();
            $countNotesSemestre = 0;

            foreach ($ues as $ue){
                if($ue->semestre_id == $sem->id){
                    foreach ($ue->matiere as $m){
                        $countNotesMatiere[$m->codeMatiere] = 0;
                    }
                    $countNotesUE[$ue->codeUE] = 0;
                }
            }
        @endphp
        <table class="table" border="box" rules="all" align="center" style="max-width: 1400px">
            <thead class="tr-title">
            <tr>
                <th colspan="2" rowspan="2"></th>
                @foreach($ues as $ue)
                    @if($ue->semestre_id == $sem->id)
                        <th colspan="{{ (count($ue->matiere)*3)+3 }}">{{ $ue->codeUE }}</th>
                    @endif
                @endforeach
                <th colspan="3" rowspan="2">SYNTH GENERALE</th>
            </tr>
            <tr>
                @foreach($ues as $ue)
                    @if($ue->semestre_id == $sem->id)
                        @foreach($ue->matiere as $m)
                            <th colspan="3">{{ $m->codeMatiere }}</th>
                        @endforeach
                        <th style="" colspan="3">SYNTH UE</th>
                    @endif
                @endforeach
            </tr>
            <tr>
                <th>N°</th>
                <th style="width: 90px">Nom et Prénom</th>
                @foreach($ues as $ue)
                    @if($ue->semestre_id == $sem->id)
                        @foreach($ue->matiere as $m)
                            <th>CC</th>
                            <th>EX</th>
                            <th>MOY</th>
                        @endforeach
                        <th>MOY</th>
                        <th>CRE</th>
                        <th>DEC</th>
                    @endif
                @endforeach
                <th>MOY FINAL</th>
                <th>CRE</th>
                <th>DEC</th>
            </tr>
            </thead>
            <tbody class="body">
            @php
                $countMoyenneUE = array();
            @endphp
            @foreach($pvs as $key2=>$pv)
                @php
                    $moyenneSemestre = 0;
                    $creditSemestre = 0;
                    $totalUEPossible = 0;
                    $totalCreditPossible = 0;
                    $countNS = 0;
                    $creditS = 0;

                    foreach ($ues as $ue){
                        if($ue->semestre_id == $sem->id){
                            $totalUEPossible++;
                            $totalCreditPossible+= $ue->credit;
                        }
                    }
                @endphp
                <tr>
                    <td>{{ $key2+1 }}</td>
                    <td style="font-size: 8px; text-align: left">{{ $pv->firstname }} {{ $pv->lastname }} </td>
                    @foreach($ues as $ue)
                        @if($ue->semestre_id == $sem->id)
                            @php
                                $moyenneUE = 0;
                                $credit = 0;
                                $countN = 0;
                            @endphp
                            @foreach($ue->matiere as $m)
                                <td class="td-result">
                                    @php
                                        $c = \Illuminate\Support\Facades\DB::table("notes")
                                            ->where("typeevaluation", "=", "cc")
                                            ->where("semestre_id", "=", $sem->id)
                                            ->where("matiere_id", "=", $m->id)
                                            ->where("inscription_id", "=", $pv->inscription_id)
                                            ->first();

                                    @endphp
                                    {{ !empty($c)? $c->moyenne  : 0}}
                                </td>
                                <td class="td-result">
                                    @php
                                        $n = \Illuminate\Support\Facades\DB::table("notes")
                                            ->where("typeevaluation", "=", "normal")
                                            ->where("semestre_id", "=", $sem->id)
                                            ->where("inscription_id", "=", $pv->inscription_id)
                                            ->where("matiere_id", "=", $m->id)
                                            ->first();

                                    @endphp
                                    {{ !empty($n)? $n->moyenne  : 0}}
                                </td>
                                <td class="td-result">
                                    @php
                                        $moyenne = 0;
                                        $cc = \Illuminate\Support\Facades\DB::table("notes")
                                            ->where("typeevaluation", "=", "cc")
                                            ->where("semestre_id", "=", $sem->id)
                                            ->where("inscription_id", "=", $pv->inscription_id)
                                            ->where("matiere_id", "=", $m->id)
                                            ->first();
                                        $normal = \Illuminate\Support\Facades\DB::table("notes")
                                            ->where("typeevaluation", "=", "normal")
                                            ->where("semestre_id", "=", $sem->id)
                                            ->where("inscription_id", "=", $pv->inscription_id)
                                            ->where("matiere_id", "=", $m->id)
                                            ->first();

                                        if(!empty($cc)){
                                            $moyenne += $cc->moyenne * 0.3;
                                        }

                                        if(!empty($normal)){
                                            $moyenne += $normal->moyenne * 0.7;
                                        }

                                        $moyenneUE += $moyenne;

                                        if($moyenne>=10){
                                            $credit += $m->creditMatiere;
                                            $countNotesMatiere[$m->codeMatiere] ++;
                                            $countN++;
                                        }

                                    @endphp
                                    {{ $moyenne }}

                                </td>
                            @endforeach
                            @php
                                $creditS += (round($moyenneUE/count($ue->matiere), 3)>=10? $ue->credit : 0);
                            @endphp
                            <td class="td-result" style="background: #eeeeee">{{ round($moyenneUE/count($ue->matiere), 3) }}</td>
                            <td class="td-result" style="background: #eeeeee">{{ (round($moyenneUE/count($ue->matiere), 3)>=10)? $ue->credit : 0 }}/{{ $ue->credit }}</td>
                            <td class="td-result" style="background: #eeeeee">
                                @php
                                    if(round($moyenneUE/count($ue->matiere), 3)>=10 && $countN>=count($ue->matiere)){
                                        echo "AC";
                                        $countNotesUE[$ue->codeUE] ++;
                                        $countNS++;
                                    }
                                    if(round($moyenneUE/count($ue->matiere), 3)>=10 && $countN<count($ue->matiere)){
                                        echo "ACC";
                                        $countNS++;
                                    }
                                    if(round($moyenneUE/count($ue->matiere), 3)<10 && round($moyenneUE/count($ue->matiere), 3)>=7){
                                        echo "NA";
                                    }

                                    if(round($moyenneUE/count($ue->matiere), 3)<7){
                                        echo "EL";
                                    }

                                    $moyenneSemestre += $moyenneUE*$ue->credit;
                                @endphp
                            </td>
                        @endif
                    @endforeach
                    <td class="td-result" style="background: #eeeeee">{{ round($moyenneSemestre/$totalCreditPossible, 3) }}</td>
                    <td class="td-result" style="background: #eeeeee">{{ $creditS }}/{{ $totalCreditPossible }}</td>
                    <td class="td-result" style="background: #eeeeee">
                        @php
                            if(round($moyenneSemestre/$totalCreditPossible, 3)>=10 && $countNS>=$totalUEPossible){
                                echo "AC";
                                $countNotesSemestre ++;
                                $creditSemestre += (round($moyenneSemestre/$totalCreditPossible, 3)>=10? $ue->credit : 0);
                            }

                            if(round($moyenneSemestre/$totalCreditPossible, 3)>=10 && $countNS<$totalUEPossible){
                                echo "ACC";
                                $creditSemestre += (round($moyenneSemestre/$totalCreditPossible, 3)>=10? $ue->credit : 0);
                            }

                            if(round($moyenneSemestre/$totalCreditPossible, 3)<10 && round($moyenneSemestre/$totalCreditPossible, 3)>=7){
                                echo "NA";
                            }

                            if(round($moyenneSemestre/$totalCreditPossible, 3)<10 && round($moyenneSemestre/$totalCreditPossible, 3)<7){
                                echo "EL";
                            }
                        @endphp
                    </td>
                </tr>
            @endforeach
            <tr>
                <td colspan="2"></td>
                @foreach($ues as $ue)
                    @if($ue->semestre_id == $sem->id)
                        @foreach($ue->matiere as $m)
                            <td colspan="2">{{ round(($countNotesMatiere[$m->codeMatiere]/count($pvs))*100, 0) }}% Réussite</td>
                            <td>{{ $countNotesMatiere[$m->codeMatiere] }}/{{ count($pvs) }}</td>
                        @endforeach
                        <td colspan="3"></td>
                    @endif
                @endforeach
                <td colspan="3" style="background: #eeeeee">{{ $countNotesSemestre }}/{{ count($pvs) }}</td>
            </tr>
            </tbody>
        </table>
        <p class="paragraphe" style="text-align:center; font-size: 12px; margin:1px;">Décision:    AC=Acquis; ACC=Acquis par compensation; NA=Non acquis; EL=Eliminé</p>
        <p class="paragraphe" style="text-align:center; font-size: 12px; margin:1px;">
            Grade et notes sur 20:
            A+ [18-20];  A [16-18[;
            B+ [14-16[;  B [13-14[;  B- [12-13[;
            C+ [11-12[;  C [10-11[;  C- [11-10[;
            D [08-09[;  E [06-08[;  F [00-06[;
        </p>


        @if(count($semestre)!=$key1+1)
            <div class="page-break"></div>
        @endif
    @endforeach

</main>
</body>
</html>