<!DOCTYPE html>
<html>
<head>
    <title>Generated by ISSAT - Fiche de description </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        @page {
            margin: 5px 12px;
        }
        .page-break {
            page-break-after: always;
        }

        h4{
            padding: 0px;
            margin: 0px;
        }

        h6{
            margin: 2px;
            padding: 2px;
        }

        h6 span{
            font-size: 12px;
            color: #ffaa04;
        }

        #body td{
            font-size: 12px;
            text-align:center;
        }

        .tr-title{
            padding: 10px;
            /*border-bottom: 1px solid #000000;*/
            background: #ffe200;
            text-align: center;
            font-weight: bold;
        }

        .td-result{
            background: rgb(221, 222, 216);
            text-align: center;
        }

        input[type=checkbox] { display: inline; }
        input[type=checkbox]:before { font-family: DejaVu Sans; }
        #watermark {
            position: fixed;
            z-index:  -1000;
            opacity: 0.2;
            left: 14%;
        }


        #body td, #body th{
            font-size: 12px;
            text-align: center;
            height: 20px;
            /*font-weight: bold;*/
            text-transform: uppercase;
        }

        #entete td, #entete th{
            font-size: 12px;
            text-align: center;
        }

        #header{
            font-size: 12px;
        }

        .borderStrong{
            border:2px solid #000000;
        }


    </style>
</head>
<body>
<div id="watermark">
    <img src="assets/images/logo/issat.png" height="100%" width="100%" />
</div>

<main id="body">
    @php
        $allCount = count($pvs[0]->notes);
        $totalUE = 0;
        $totalUEExist = 0;
        $totalMatiereExist = 0;
        $ueDone = array();
    @endphp


    @foreach($semestre as $sem)
        @php
            $count=0;
            $moyennesTotale = array();
            $creditTotale = array();
            $totalNotesUp = array();
            $totalNotesUpMatiere = array();
            $moyenneGenerale = 0;
            $totalReussite = 0;
            $minimum = 20;
            $maximum = 0;

            foreach ($pvs as $n=>$pv){
                $creditTotale[$pv->inscription_id] = 0;
                $moyennesTotale[$pv->inscription_id] = 0;
            }

            foreach($ues as $n=>$ue){
                $totalNotesUp[$n] = 0;
                $totalNotesUpMatiere[$n] = array();
            }

        @endphp
        @foreach($pvs as $k=>$pv)
            @if($count==0)
                @foreach($ues as $r=>$ue)
                    @if($ue->semestre_id==$sem->id)
                        @php
                            $totalUEExist ++;
                            $totalMatiereExist += count($ue->matiere);
                        @endphp
                    @endif
                    @foreach($ue->matiere as $m)
                        @php
                            $totalNotesUpMatiere[$r][$m->id] =  0;
                        @endphp
                    @endforeach
                @endforeach
                @break
            @endif
        @endforeach

        @for($i=0; $i<$totalUEExist; $i+=2)
            @include("pdf.entete-pv")
            <hr style="background-color: #999999; border: 1px dashed #cccccc">
            @php
                $count=0;
                $uesArrays = array();
            @endphp
            <p width="100%" style="text-align: center; font-size: 20px">PROCES VERBAL DE NOTES DE FIN DE SEMESTRE {{ $sem->libelleSemestre }} ({{ $pvs[0]->numeroAnnee }}-{{ intval($pvs[0]->numeroAnnee)+1 }})</p>
            <p width="100%" style="text-align: center; font-size: 16px">{{ $pvs[0]->codeSpecialite }} = {{ $pvs[0]->libelleSpecialite }} (SEMESTRE {{ $sem->libelleSemestre }})</p>

            <table class="table" border="box" rules="all" width="100%" align="center">
                @foreach($pvs as $o=>$pv)
                    @php
                        $totalNotes = 0;
                        $totalCredit = 0;
                        $countMatiere = 0;
                    @endphp

                    @if($count==0)
                        <tr class="tr-title">
                            <td style="border: none"></td>
                            <td style="border: none"></td>
                            <td style="border: none"></td>
                            @foreach($ues as $ue)
                                @if($ue->semestre_id==$sem->id && !in_array($ue->id, $ueDone))
                                    @if(count($ue->matiere)>0 && $countMatiere<2)
                                        @php
                                            $countMatiere++;
                                            array_push($ueDone, $ue->id);
                                            array_push($uesArrays, $ue->id);
                                        @endphp
                                        <td colspan="{{  (count($ue->matiere)*3)+4 }}">({{ $ue->codeUE }})<br><span style="font-size: 8px">{{ $ue->libelleUE }}</span></td>
                                    @else
                                        @php
                                            $countMatiere=0;
                                        @endphp
                                        @break
                                    @endif
                                @endif
                            @endforeach

                            @if($i==$totalUEExist-1)
                                <td colspan="4" rowspan="2"  class="borderStrong">SYNTHESE GENERALE</td>
                            @endif
                        </tr>

                        <tr class="tr-title">
                            <td style="border: none"></td>
                            <td style="border: none"></td>
                            <td style="border: none"></td>
                            @foreach($ues as $z=>$ue)
                                @if($ue->semestre_id==$sem->id && in_array($ue->id, $uesArrays))
                                    @if(count($ue->matiere)>0 && $countMatiere<2)
                                        @php
                                            $countMatiere++;
                                            array_push($ueDone, $ue->id)
                                        @endphp
                                        @foreach($ue->matiere as $m)
                                            <td colspan="3">({{ $m->codeMatiere }}) <br><span style="font-size: 8px"> {{ $m->libelleMatiere }}</span></td>
                                        @endforeach
                                        <td colspan="4"><span class="longText">SYNTHESE UE {{ $ue->codeUE }}</span></td>
                                    @else
                                        @php
                                            $countMatiere=0;
                                        @endphp
                                        @break
                                    @endif

                                @endif
                            @endforeach
                        </tr>
                        <tr class="tr-title">
                            <td>#</td>
                            <td>MATRICULE</td>
                            <td>NOM(S) & PRENOM(S)</td>
                            @foreach($ues as $w=>$ue)
                                @if($ue->semestre_id==$sem->id &&  in_array($ue->id, $uesArrays))
                                    @if(count($ue->matiere)>0 )
                                        @foreach($ue->matiere as $m)
                                            <td>CC</td>
                                            <td>EX</td>
                                            <td>MOY</td>
                                        @endforeach
                                        <td>MOY UE</td>
                                        <td>GRA</td>
                                        <td>CRE</td>
                                        <td>DEC</td>
                                    @endif
                                @endif
                            @endforeach

                            @if($i==$totalUEExist-1)
                                <td class="borderStrong">MOY UE</td>
                                <td class="borderStrong">GRA</td>
                                <td class="borderStrong">CRE</td>
                                <td class="borderStrong">DEC</td>
                            @endif
                        </tr>

                        <tr>
                            <td>{{ ++$count }}</td>
                            <td>{{ $pv->dossier->matriculeDossier }}</td>
                            <td style="text-align: left">{{ \Illuminate\Support\Str::upper($pv->lastname) }} {{ \Illuminate\Support\Str::upper($pv->firstname) }}</td>
                            @foreach($ues as $z=>$ue)
                                @if($ue->semestre_id==$sem->id && in_array($ue->id, $uesArrays))
                                    @if(count($ue->matiere)>0)
                                        @php
                                            $countMatiere++;
                                            $moyenneUE = 0;
                                            $creditUE = 0;
                                        @endphp
                                        @foreach($ue->matiere as $m)
                                            @php
                                                $notecc = \App\Models\Note::where("inscription_id", "=", $pv->inscription_id)
                                                        ->where("semestre_id", "=", $sem->id)
                                                        ->where("matiere_id", "=", $m->id)
                                                        ->where("typeevaluation", "=", "cc")->first();

                                                $notenormal = \App\Models\Note::where("inscription_id", "=", $pv->inscription_id)
                                                        ->where("semestre_id", "=", $sem->id)
                                                        ->where("matiere_id", "=", $m->id)
                                                        ->where("typeevaluation", "=", "normal")->first();

                                                $cc = !empty($notecc)? $notecc->moyenne*0.3 : 0;
                                                $normal = !empty($notenormal)? $notenormal->moyenne*0.7 : 0;
                                                $moyenne = $cc+$normal;
                                                $moyenneUE += round($moyenne/count($ue->matiere), 3);
                                                if($moyenne>=10){
                                                    $creditUE += $m->creditMatiere;
                                                    $totalNotesUpMatiere[$z][$m->id] = $totalNotesUpMatiere[$z][$m->id] +1;
                                                }


                                                $moyennesTotale[$pv->inscription_id] += $moyenne;

                                            @endphp
                                            <td>{{ round($cc/0.3, 3) }}</td>
                                            <td>{{ round($normal/0.7, 3) }}</td>
                                            <td>{{ $moyenne }}</td>
                                        @endforeach
                                        @php
                                            if($moyenneUE >= 10){
                                                $totalNotesUp[$z] = $totalNotesUp[$z]+1;
                                            }
                                        @endphp
                                        <td>{{ $moyenneUE }}</td>
                                        <td>
                                            @php

                                                if ($moyenneUE>=16){
                                                    echo "A";
                                                }

                                                if ($moyenneUE>=14 && $moyenneUE<16){
                                                    echo "B";
                                                }

                                                if ($moyenneUE>=12 && $moyenneUE<14){
                                                    echo "C";
                                                }

                                                if ($moyenneUE>=10 && $moyenneUE<12){
                                                    echo "D";
                                                }

                                                if ($moyenneUE>=8 && $moyenneUE<10){
                                                    echo "E";
                                                }

                                                if ($moyenneUE<8){
                                                    echo "F";
                                                }
                                                $creditTotale[$pv->inscription_id] += $creditUE;
                                            @endphp
                                        </td>
                                        <td>{{ $creditUE }}</td>
                                        <td>
                                            @php
                                                if ($moyenneUE>=10){
                                                    echo "AC";
                                                }
                                                if ($moyenneUE>=9 && $moyenneUE<10 ){
                                                    echo "ACC";
                                                }
                                                if ($moyenneUE>=0 && $moyenneUE<9 ){
                                                    echo "NA";
                                                }
                                            @endphp
                                        </td>
                                    @else
                                        @php
                                            $countMatiere=0;
                                        @endphp
                                        @break
                                    @endif
                                @endif
                            @endforeach

                            @if($i==$totalUEExist-1)
                                @php
                                    $moyenneFinaleGenerale = round($moyennesTotale[$pv->inscription_id]/$totalMatiereExist, 3);
                                @endphp
                                <td>{{ $moyenneFinaleGenerale }}</td>
                                <td>
                                    @php
                                        $moyenneGenerale += $moyenneFinaleGenerale;
                                        if ($moyenneFinaleGenerale>=16){
                                            echo "A";
                                        }

                                        if ($moyenneFinaleGenerale>=14 && $moyenneFinaleGenerale<16){
                                            echo "B";
                                        }

                                        if ($moyenneFinaleGenerale>=12 && $moyenneFinaleGenerale<14){
                                            echo "C";
                                        }

                                        if ($moyenneFinaleGenerale>=10 && $moyenneFinaleGenerale<12){
                                            echo "D";
                                        }

                                        if ($moyenneFinaleGenerale>=8 && $moyenneFinaleGenerale<10){
                                            echo "E";
                                        }

                                        if ($moyenneFinaleGenerale<8){
                                            echo "F";
                                        }
                                    @endphp
                                </td>
                                <td>{{ $creditTotale[$pv->inscription_id] }}</td>
                                <td>
                                    @php
                                        if ($moyenneFinaleGenerale>=10){
                                            echo "AC";
                                            $totalReussite ++;
                                        }
                                        if ($moyenneFinaleGenerale>=9 && $moyenneFinaleGenerale<10 ){
                                            echo "ACC";
                                        }
                                        if ($moyenneFinaleGenerale>=0 && $moyenneFinaleGenerale<9 ){
                                            echo "NA";
                                        }

                                        if($minimum>$moyenneFinaleGenerale){
                                            $minimum = $moyenneFinaleGenerale;
                                        }

                                        if($maximum<$moyenneFinaleGenerale){
                                            $maximum = $moyenneFinaleGenerale;
                                        }
                                    @endphp
                                </td>
                            @endif
                        </tr>
                    @else
                        <tr>
                            <td>{{ ++$count }}</td>
                            <td>{{ $pv->dossier->matriculeDossier }}</td>
                            <td  style="text-align: left">{{ \Illuminate\Support\Str::upper($pv->lastname) }} {{ \Illuminate\Support\Str::upper($pv->firstname) }}</td>
                            @foreach($ues as $z=>$ue)
                                @if($ue->semestre_id==$sem->id && in_array($ue->id, $uesArrays))
                                    @if(count($ue->matiere)>0)
                                        @php
                                            $moyenneUE = 0;
                                            $creditUE = 0;
                                            $total = 0;
                                        @endphp
                                        @foreach($ue->matiere as $m)
                                            @php
                                                $notecc = \App\Models\Note::where("inscription_id", "=", $pv->inscription_id)
                                                        ->where("semestre_id", "=", $sem->id)
                                                        ->where("matiere_id", "=", $m->id)
                                                        ->where("typeevaluation", "=", "cc")->first();

                                                $notenormal = \App\Models\Note::where("inscription_id", "=", $pv->inscription_id)
                                                        ->where("semestre_id", "=", $sem->id)
                                                        ->where("matiere_id", "=", $m->id)
                                                        ->where("typeevaluation", "=", "normal")->first();

                                                $cc = !empty($notecc)? $notecc->moyenne*0.3 : 0;
                                                $normal = !empty($notenormal)? $notenormal->moyenne*0.7 : 0;
                                                $moyenne = $cc+$normal;
                                                $moyenneUE += round($moyenne/count($ue->matiere), 3);
                                                if($moyenne>=10){
                                                    $creditUE += $m->creditMatiere;
                                                    $totalNotesUpMatiere[$z][$m->id] = $totalNotesUpMatiere[$z][$m->id] +1;
                                                }


                                                $moyennesTotale[$pv->inscription_id] += $moyenne;

                                            @endphp
                                            <td>{{ round($cc/0.3, 3) }}</td>
                                            <td>{{ round($normal/0.7, 3) }}</td>
                                            <td>{{ $moyenne }}</td>
                                        @endforeach
                                        @php
                                            if($moyenneUE >=10){
                                                ++$totalNotesUp[$z];
                                            }
                                        @endphp
                                        <td>{{ $moyenneUE }}</td>
                                        <td>
                                            @php

                                                if ($moyenneUE>=16){
                                                    echo "A";
                                                }

                                                if ($moyenneUE>=14 && $moyenneUE<16){
                                                    echo "B";
                                                }

                                                if ($moyenneUE>=12 && $moyenneUE<14){
                                                    echo "C";
                                                }

                                                if ($moyenneUE>=10 && $moyenneUE<12){
                                                    echo "D";
                                                }

                                                if ($moyenneUE>=8 && $moyenneUE<10){
                                                    echo "E";
                                                }

                                                if ($moyenneUE<8){
                                                    echo "F";
                                                }

                                                $creditTotale[$pv->inscription_id] += $creditUE;

                                            @endphp
                                        </td>
                                        <td>{{ $creditUE }}</td>
                                        <td>
                                            @php
                                                if ($moyenneUE>=10){
                                                    echo "AC";
                                                }
                                                if ($moyenneUE>=9 && $moyenneUE<10 ){
                                                    echo "ACC";
                                                }
                                                if ($moyenneUE>=0 && $moyenneUE<9 ){
                                                    echo "NA";
                                                }
                                            @endphp
                                        </td>
                                    @endif
                                @endif
                            @endforeach

                            @if($i==$totalUEExist-1)
                                @php
                                    $moyenneFinaleGenerale = round($moyennesTotale[$pv->inscription_id]/$totalMatiereExist, 3);
                                @endphp
                                <td>{{ $moyenneFinaleGenerale }}</td>
                                <td>
                                    @php
                                        $moyenneGenerale += $moyenneFinaleGenerale;
                                        if ($moyenneFinaleGenerale>=16){
                                            echo "A";
                                        }

                                        if ($moyenneFinaleGenerale>=14 && $moyenneFinaleGenerale<16){
                                            echo "B";
                                        }

                                        if ($moyenneFinaleGenerale>=12 && $moyenneFinaleGenerale<14){
                                            echo "C";
                                        }

                                        if ($moyenneFinaleGenerale>=10 && $moyenneFinaleGenerale<12){
                                            echo "D";
                                        }

                                        if ($moyenneFinaleGenerale>=8 && $moyenneFinaleGenerale<10){
                                            echo "E";
                                        }

                                        if ($moyenneFinaleGenerale<8){
                                            echo "F";
                                        }
                                    @endphp
                                </td>
                                <td>{{ $creditTotale[$pv->inscription_id] }}</td>
                                <td>
                                    @php
                                        if ($moyenneFinaleGenerale>=10){
                                            echo "AC";
                                            $totalReussite ++;
                                        }
                                        if ($moyenneFinaleGenerale>=9 && $moyenneFinaleGenerale<10 ){
                                            echo "ACC";
                                        }
                                        if ($moyenneFinaleGenerale>=0 && $moyenneFinaleGenerale<9 ){
                                            echo "NA";
                                        }

                                        if($minimum>$moyenneFinaleGenerale){
                                            $minimum = $moyenneFinaleGenerale;
                                        }

                                        if($maximum<$moyenneFinaleGenerale){
                                            $maximum = $moyenneFinaleGenerale;
                                        }
                                    @endphp
                                </td>
                            @endif
                        </tr>
                    @endif

                    @if($count==count($pvs))
                        <tr>
                            <td  colspan="3"></td>
                            @foreach($ues as $l=>$ue)
                                @if($ue->semestre_id==$sem->id && in_array($ue->id, $uesArrays))
                                    @if(count($ue->matiere)>0)
                                        @php
                                            $moyenneUE = 0;
                                            $creditUE = 0;
                                        @endphp
                                        @foreach($ue->matiere as $m)
                                            <td colspan="2"></td>
                                            <td>{{ $totalNotesUpMatiere[$l][$m->id] }}/{{ count($pvs) }} ({{ round(($totalNotesUpMatiere[$l][$m->id]*100)/count($pvs), 2) }}%)</td>
                                        @endforeach
                                        <td>{{ $totalNotesUp[$l] }}/{{ count($pvs) }}</td>
                                        <td colspan="3"> {{ round(($totalNotesUp[$l]*100)/count($pvs), 2) }}% de Réussite</td>
                                    @endif
                                @endif
                            @endforeach
                            <td colspan="4"></td>
                        </tr>
                    @endif
                @endforeach
            </table>
            <p class="paragraphe" style="text-align:center; font-size: 12px; margin:1px;">Décision:    AC=Capitalisé; ACC=Capitalisé Non transférable; NA=Non Capitalisé; EL=Eliminé</p>
            <p class="paragraphe" style="text-align:center; font-size: 12px; margin:1px;">
                Grade et notes sur 20:
                A+ [18-20];  A [16-18[;
                B+ [14-16[;  B [13-14[;  B- [12-13[;
                C+ [11-12[;  C [10-11[;  C- [11-10[;
                D [08-09[;  E [06-08[;  F [00-06[;
            </p>
            <div class="page-break"></div>
        @endfor
        <table class="table" border="box" rules="all" width="90%" align="center" style="margin: 50px">
            <tr>
                <td>Moyenne générale</td>
                <td>{{ round($moyenneGenerale/count($pvs),3) }}</td>
            </tr>
            <tr>
                <td>Taux de réussite général</td>
                <td>{{ ($totalReussite*100)/count($pvs) }}%</td>
            </tr>
            <tr>
                <td>Nombre total de reussite</td>
                <td>{{ $totalReussite }}</td>
            </tr>
            <tr>
                <td>Moyenne maximale</td>
                <td>{{ $maximum }}</td>
            </tr>
            <tr>
                <td>Moyenne minimale</td>
                <td>{{ $minimum }}</td>
            </tr>
        </table>
        <div class="page-break"></div>
    @endforeach

</main>
</body>
</html>