<!DOCTYPE html>
<html>
<head>
    <title>Generated by IFPSTA - Fiche de scolarité </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        @page {
            margin: 5px 12px;
        }
        .page-break {
            page-break-after: always;
        }

        h4{
            padding: 0px;
            margin: 0px;
        }

        h6{
            margin: 2px;
            padding: 2px;
        }

        h6 span{
            font-size: 14px;
            color: #ffaa04;
        }

        #body td{
            font-size: 14px;
            text-align:center;
        }

        .tr-title{
            padding: 10px;
            /*border-bottom: 1px solid #000000;*/
            background: ##e1e3e1;
            text-align: center;
            color:#000000;
        }

        .td-result{
            background: rgb(221, 222, 216);
            text-align: center;
        }

        input[type=checkbox] { display: inline; }
        input[type=checkbox]:before { font-family: DejaVu Sans; }
        #watermark {
            position: fixed;

            /** Change image dimensions**/
            /*width:    20cm;*/
            /*height:   20cm;*/

            /** Your watermark should be behind every content**/
            z-index:  -1000;
            opacity: 0.2;
            left: 6%;
        }

        .longText{
            /*transform: rotate(-90deg);*/

            /*-webkit-transform: rotate(-90deg);*/

            /*!* Firefox *!*/
            /*-moz-transform: rotate(-90deg);*/

            /*!* IE *!*/
            /*-ms-transform: rotate(-90deg);*/

            /*!* Opera *!*/
            /*-o-transform: rotate(-90deg);*/

            /*!* Internet Explorer *!*/
            /*filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);*/
        }

        #body td, #body th{
            font-size: 14px;
            text-align: center;
            height: 30px;
            font-weight: bold;
            text-transform: uppercase;
        }

        #entete td, #entete th{
            font-size: 14px;
            text-align: center;
        }

        /*tbody td{*/
        /*font-size: 5px;*/
        /*}*/

        .bg-danger{
            background-color: rgba(255, 0, 0, 0.49);
        }
        .bg-success{
            background-color: rgba(1, 203, 114, 0.51);
        }

        #header{
            font-size: 14px;
        }

        .borderStrong{
            border:2px solid #000000;
        }
        
        #body p{
            font-family: arial;
            text-transform: italic;
        }

    </style>
</head>
<body>
<div id="watermark">
    <img src="{{ asset("") }}assets/images/logo/issat.png" width="100%" style="margin-top: 200px"/>
    
    <img src="{{ asset("") }}assets/images/logo/issat.png" width="100%" style="margin-top: 200px"/>
</div>

<main id="body" style="padding: 2px 10px">
    <table border="box" rules="none" width="100%">
        <tr>
            <td colspan="2">
                @include("pdf.entete-pv")
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <h2 style="text-transform: uppercase; text-align: center; text-transform: uppercase">Reçu de verssement</h2>
            </td>
        </tr>
        
        <tr>
            <td width="50%">
                <table class="table table-bordered"  border="box" rules="all" width="100%">
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Dossier N° :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->inscription->dossier->numeroDossier }}</p></td>
                    </tr>
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Matricule N° :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->inscription->dossier->matriculeDossier }}</p></td>
                    </tr>
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Nom et prénom :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->inscription->dossier->etudiant->firstname }} {{ $verssement->inscription->dossier->etudiant->lastname }}</p></td>
                    </tr>
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Matricule N° :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->inscription->dossier->matriculeDossier }}</p></td>
                    </tr>
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Spécialité :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->scolarite->specialite->libelleSpecialite }}</p></td>
                    </tr>
                </table>
            </td>
    
            <td width="50%">
                <table class="table table-bordered" border="box" rules="all" width="100%">
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Référence :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->codeVerssement }}</p></td>
                    </tr>
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Intitulé :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->scolarite->compte->libelleCompte }}</p></td>
                    </tr>
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Montant :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->montantVerssement }}</p></td>
                    </tr>
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Date :</h4></td>
                        <td style="text-align:left"><p>{{ date("d/m/Y", strtotime($verssement->dateVerssement)) }}</p></td>
                    </tr>
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Description :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->descriptionVerssement }}</p></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr style="border:none;">
            <td></td>
            <td style="text-align:center; border-bottom:1px dashed #000000"><h4>Visa</h4></td>
        </tr>
    </table>
    <br><br>
    
    <hr style="border:1px dashed #999999">
    
    <table border="box" rules="none" width="100%">
        <tr>
            <td colspan="2">
                @include("pdf.entete-pv")
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <h2 style="text-transform: uppercase; text-align: center; text-transform: uppercase">Reçu de verssement</h2>
            </td>
        </tr>
        
        <tr>
            <td width="50%">
                <table class="table table-bordered"  border="box" rules="all" width="100%">
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Dossier N° :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->inscription->dossier->numeroDossier }}</p></td>
                    </tr>
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Matricule N° :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->inscription->dossier->matriculeDossier }}</p></td>
                    </tr>
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Nom et prénom :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->inscription->dossier->etudiant->firstname }} {{ $verssement->inscription->dossier->etudiant->lastname }}</p></td>
                    </tr>
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Matricule N° :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->inscription->dossier->matriculeDossier }}</p></td>
                    </tr>
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Spécialité :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->scolarite->specialite->libelleSpecialite }}</p></td>
                    </tr>
                </table>
            </td>
    
            <td width="50%">
                <table class="table table-bordered" border="box" rules="all" width="100%">
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Référence :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->codeVerssement }}</p></td>
                    </tr>
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Intitulé :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->scolarite->compte->libelleCompte }}</p></td>
                    </tr>
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Montant :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->montantVerssement }}</p></td>
                    </tr>
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Date :</h4></td>
                        <td style="text-align:left"><p>{{ date("d/m/Y", strtotime($verssement->dateVerssement)) }}</p></td>
                    </tr>
                    <tr>
                        <td class="tr-title" style="text-align:left"><h4>Description :</h4></td>
                        <td style="text-align:left"><p>{{ $verssement->descriptionVerssement }}</p></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr style="border:none;">
            <td></td>
            <td style="text-align:center; border-bottom:1px dashed #000000"><h4>Visa</h4></td>
        </tr>
    </table>
</main>
</body>
</html>