<!DOCTYPE html>
<html>
<head>
    <title>Generated by IFPSTA - Fiche de scolarité </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        @page {
            margin: 5px 12px;
        }
        .page-break {
            page-break-after: always;
        }

        h4{
            padding: 0px;
            margin: 0px;
        }

        h6{
            margin: 2px;
            padding: 2px;
        }

        h6 span{
            font-size: 14px;
            color: #ffaa04;
        }

        #body td{
            font-size: 14px;
            text-align:center;
        }

        .tr-title{
            padding: 10px;
            /*border-bottom: 1px solid #000000;*/
            background: ##e1e3e1;
            text-align: center;
            color:#000000;
        }

        .td-result{
            background: rgb(221, 222, 216);
            text-align: center;
        }

        input[type=checkbox] { display: inline; }
        input[type=checkbox]:before { font-family: DejaVu Sans; }
        #watermark {
            position: fixed;

            /** Change image dimensions**/
            /*width:    20cm;*/
            /*height:   20cm;*/

            /** Your watermark should be behind every content**/
            z-index:  -1000;
            opacity: 0.2;
            left: 6%;
        }

        .longText{
            /*transform: rotate(-90deg);*/

            /*-webkit-transform: rotate(-90deg);*/

            /*!* Firefox *!*/
            /*-moz-transform: rotate(-90deg);*/

            /*!* IE *!*/
            /*-ms-transform: rotate(-90deg);*/

            /*!* Opera *!*/
            /*-o-transform: rotate(-90deg);*/

            /*!* Internet Explorer *!*/
            /*filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);*/
        }

        #body td, #body th{
            font-size: 14px;
            text-align: center;
            height: 30px;
            font-weight: bold;
            text-transform: uppercase;
        }

        #entete td, #entete th{
            font-size: 14px;
            text-align: center;
        }

        /*tbody td{*/
        /*font-size: 5px;*/
        /*}*/

        .bg-danger{
            background-color: rgba(255, 0, 0, 0.49);
        }
        .bg-success{
            background-color: rgba(1, 203, 114, 0.51);
        }

        #header{
            font-size: 14px;
        }

        .borderStrong{
            border:2px solid #000000;
        }


    </style>
</head>
<body>
<div id="watermark">
    <img src="{{ asset("") }}assets/images/logo/issat.png" width="100%" style="margin-top: 200px"/>
</div>
<header>
    @include("pdf.entete-pv")
</header>

<hr style="background-color: #999999; border: 1px dashed #cccccc">
<h4 style="text-transform: uppercase; text-align: center">Fiche de solvabilité</h4>
<h5 style="text-transform: uppercase; text-align: center">{{ $specialite->codeSpecialite }}={{ $specialite->libelleSpecialite }}</h5>

<main id="body" style="padding: 20px">
    @if(count($inscription)>0)
        <table border="box" rules="all" width="100%">
            <thead class="tr-title">
                <th width="4%">#</th>
                <th width="12%">Matricule</th>
                <th width="34%">Nom et prénom</th>
                <th>Debit</th>
                <th>Credit</th>
                <th>Ecart</th>
            </thead>
            <tbody>
            @php
                $totalVT = 0;
            @endphp
                @foreach($inscription as $i=>$inc)
                    <tr>
                        <td>{{ ++$i }}</td>
                        <td>{{ $inc->dossier->matriculeDossier }}</td>
                        <td>{{ $inc->dossier->etudiant->firstname }} {{ $inc->dossier->etudiant->lastname }} </td>
                        <td>
                            @php
                                $totalV = 0;
                                foreach($inc->verssement as $v){
                                    $totalV += $v->montantVerssement;
                                }
                                $totalVT+= $totalV;
                            @endphp
                            {{ $totalV }}</td>
                        <td>
                            {{ $total }}
                        </td>
                        <td >{{ $totalV - $total }}</td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot class="tr-title">
                <th colspan="3">TOTAL SOLDE</th>
                <th>{{ $totalVT }}</th>
                <th>{{ $total*count($inscription) }}</th>
                <th>{{ $totalVT - ($total*count($inscription)) }}</th>
            </tfoot>
        </table>
    @endif
</main>
</body>
</html>