<!DOCTYPE html>
<html>
<head>
    <title>Generated by ISSAT - Fiche de description </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        @page {
            margin: 10px 30px;
        }
        .page-break {
            page-break-after: always;
        }

        h4{
            padding: 0px;
            margin: 0px;
        }

        h6{
            margin: 2px;
            padding: 2px;
        }

        h6 span{
            font-size: 8px;
            color: #ffaa04;
        }

        #body td{
            font-size: 5px;
        }

        .tr-body{
            padding: 10px;
            border-bottom: 1px solid #000000;
            background: rgba(255, 226, 0, 0.4);
            text-align: center;
        }

        .tr-title{
            padding: 10px;
            background: rgba(255, 226, 0, 0.65);
            text-align: center;
        }

        .td-result{
            background: rgb(221, 222, 216);
            text-align: center;
        }

        input[type=checkbox] { display: inline; }
        input[type=checkbox]:before { font-family: DejaVu Sans; }
        #watermark {
            position: fixed;

            /** Change image dimensions**/
            width:    20cm;
            /*height:   20cm;*/

            /** Your watermark should be behind every content**/
            z-index:  -1000;
            opacity: 0.2;
            left: 1%;
            top:5%;
        }

        .longText{
            /*transform: rotate(-90deg);*/

            /*-webkit-transform: rotate(-90deg);*/

            /*!* Firefox *!*/
            /*-moz-transform: rotate(-90deg);*/

            /*!* IE *!*/
            /*-ms-transform: rotate(-90deg);*/

            /*!* Opera *!*/
            /*-o-transform: rotate(-90deg);*/

            /*!* Internet Explorer *!*/
            /*filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);*/
        }

        #body td, #body th{
            font-size: 10px;
        }

        #entete td, #entete th{
            font-size: 8px;
            text-align: center;
        }

        #entete-corps td, #entete-corps th{
            font-size: 10px;
            text-align: left;
        }

        /*tbody td{*/
        /*font-size: 5px;*/
        /*}*/

        .bg-danger{
            background-color: rgba(255, 0, 0, 0.49);
        }
        .bg-success{
            background-color: rgba(1, 203, 114, 0.51);
        }

        #header{
            font-size: 12px;
        }

        .paragraphe{
            font-size: 10px;
        }


    </style>
</head>
<body>
<div id="watermark">
    <img src="{{ asset("") }}assets/images/logo/issat.png" height="70%" width="100%" />
</div>
<main id="body">
    @php
        $rangs = array();
        $indexRang = 1;
    @endphp

    @foreach($specialite as $sp)
        @if(count($sp->choice)>0)

            @foreach($sp->choice as $c)
                @if($c->etat==1)
                    @php
                        $rangs[$c->inscription_id] = array("rang"=> $indexRang, "moyenne"=>null) ;
                        $indexRang++;
                    @endphp
                @endif
            @endforeach
        @endif
    @endforeach

    @foreach($specialite as $sp)
        @if(count($sp->choice)>0)

            @foreach($sp->choice as $c)
                @if($c->etat==1)
                    @php
                        $creditTT = 0;
                        $creditRecuTT = 0;
                        $moyenneTT = 0;
                        $nbUET = 0;

                    @endphp
                    @foreach($semestres as$i=>$s)
                        @php
                            $creditT = 0;
                            $creditRecuT = 0;
                            $moyenneT = 0;
                            $nbUE = 0;

                        @endphp
                        @if(count($c->specialite->ues)>0)

                            @php
                                $same = "";

                            @endphp

                            @foreach($c->specialite->ues as $ue)
                                @if($ue->semestre->libelleSemestre == $s->libelleSemestre)
                                    @if(count($ue->matiere)>0)
                                        @foreach($ue->matiere as $ec)
                                            @php
                                                $cc = \App\Models\Note::where("matiere_id", "=", $ec->id)
                                                ->where("inscription_id", "=", $c->inscription->id)
                                                ->where("semestre_id", "=", $s->id)
                                                ->where("typeevaluation", "=", "cc")
                                                ->first();


                                                $exam = \App\Models\Note::where("matiere_id", "=", $ec->id)
                                                ->where("inscription_id", "=", $c->inscription->id)
                                                ->where("semestre_id", "=", $s->id)
                                                ->where("typeevaluation", "=", "normal")
                                                ->first();

                                                $notecc = !empty($cc)? $cc->moyenne*0.3 : 0;
                                                $noteex = !empty($exam)? $exam->moyenne*0.7 : 0;
                                                $moyenne = $notecc+$noteex;
                                                $moyenneT += $moyenne;
                                                $moyenneTT += $moyenne;

                                                $nbUE ++;
                                                $nbUET ++;


                                                $creditT += $ec->creditMatiere;
                                                $creditTT += $ec->creditMatiere;

                                                if($moyenne>=10){
                                                    $creditRecuT += $ec->creditMatiere;
                                                    $creditRecuTT += $ec->creditMatiere;
                                                }

                                            @endphp


                                            @php
                                                $same=$ue->codeUE;
                                            @endphp
                                        @endforeach
                                    @endif

                                @endif
                            @endforeach
                        @endif
                    @endforeach
                    @php
                        $rangs[$c->inscription_id]["moyenne"] = round($moyenneTT/$nbUET, 3) ;
                    @endphp
                @endif
            @endforeach
        @endif
    @endforeach

    @php
        $classement = array();
        $i = count($rangs);
        $items = $rangs;
        usort($rangs, function($a, $b){ return $a['moyenne'] > $b['moyenne'];});

        foreach($rangs as $j=>$r){
            $r["rang"] = $i;
            $i--;
            foreach($items as $k=>$l){
                if($l["moyenne"]==$r["moyenne"]){
                    $classement[$k] = $r;
                }
            }
        }

    @endphp


    @foreach($specialite as $sp)
        @if(count($sp->choice)>0)

            @php
                $headinscription = array();
                $bodyinscription = array();
            @endphp


            @foreach($sp->choice as $c)
                @if($c->etat==1 && !in_array($sp, $headinscription))
                    @include("pdf.bulletins.entete-releve")

                    <h2 style="text-align: center; line-height: 0;">RELEVE DE NOTES</h2>
                    <hr style="background-color: #999999; border: 1px dashed #cccccc">

                    <table class="table " border="box" rules="none" align="center" id="entete-corps" style="width: 100%">
                        <tr>
                            <td width=""><b>Filière</b></td>
                            <td width="">: {{ $c->specialite->filiere->libelleFiliere }}</td>
                            <td width=""><b>Specialite</b></td>
                            <td colspan="4">: {{ $c->specialite->libelleSpecialite }}</td>
                        </tr>
                        <tr>
                            <td width=""><b>Nom de l'étudiant</b></td>
                            <td width="">: {{ $c->inscription->dossier->etudiant->lastname }} {{ $c->inscription->dossier->etudiant->firstname }}</td>
                        </tr>
                        <tr>
                            <td width=""><b>Né(e) le</b></td>
                            <td width="">: {{ $c->inscription->dossier->etudiant->birthday }}</td>
                            <td width=""><b>à </b></td>
                            <td width="">: {{ $c->inscription->dossier->etudiant->birthplace}}</td>
                            <td width=""><b>Sexe</b></td>
                            <td width="">:  {{ $c->inscription->dossier->etudiant->sexe }}</td>
                        </tr>
                        <tr>
                            <td width=""><b>Matricule</b></td>
                            <td width="">:  {{ $c->inscription->dossier->matriculeDossier}}</td>
                            <td width=""><b>Année</b></td>
                            <td width="">:  {{ $c->inscription->anneacademique->numeroAnnee }}</td>
                            <td width=""><b>Niveau</b></td>
                            <td width="">:  {{ $c->inscription->level->numeroLevel }}</td>
                        </tr>
                    </table>

                    <hr style="background-color: #999999; border: 1px dashed #cccccc">
                    @php
                        $creditTT = 0;
                        $creditRecuTT = 0;
                        $moyenneTT = 0;
                        $nbUET = 0;

                    @endphp
                    @foreach($semestres as$i=>$s)
                        @php
                            $creditT = 0;
                            $creditRecuT = 0;
                            $moyenneT = 0;
                            $nbUE = 0;

                        @endphp

                        @if(count($c->specialite->ues)>0)

                            <table class="table" border="box" rules="all" align="center" width="100%">
                                <tr>
                                    <td>
                                        <b>SEMESTRE {{ $s->libelleSemestre }}</b>
                                        <table class="table" border="box" rules="all" width="100%" align="center">
                                            <thead class="tr-title">
                                            <th width="10%">Code UE</th>
                                            <th width="10%">Code EC</th>
                                            <th width="32%">Intitulé de l'EC</th>
                                            <th width="8%">CC</th>
                                            <th width="8%">EXAM</th>
                                            <th width="8%">Note/20</th>
                                            <th width="8%">Grade</th>
                                            <th width="8%">Décision</th>
                                            <th width="8%">Crédit</th>
                                            </thead>
                                            <tbody>
                                            @php
                                                $same = "";

                                            @endphp


                                            @foreach($c->specialite->ues as $ue)
                                                @if($ue->semestre->libelleSemestre == $s->libelleSemestre)
                                                    @if(count($ue->matiere)>0)
                                                        @foreach($ue->matiere as $ec)
                                                            @php
                                                                $cc = \App\Models\Note::where("matiere_id", "=", $ec->id)
                                                                ->where("inscription_id", "=", $c->inscription->id)
                                                                ->where("semestre_id", "=", $s->id)
                                                                ->where("typeevaluation", "=", "cc")
                                                                ->first();


                                                                $exam = \App\Models\Note::where("matiere_id", "=", $ec->id)
                                                                ->where("inscription_id", "=", $c->inscription->id)
                                                                ->where("semestre_id", "=", $s->id)
                                                                ->where("typeevaluation", "=", "normal")
                                                                ->first();

                                                                $notecc = !empty($cc)? $cc->moyenne*0.3 : 0;
                                                                $noteex = !empty($exam)? $exam->moyenne*0.7 : 0;
                                                                $moyenne = $notecc+$noteex;
                                                                $moyenneT += $moyenne;
                                                                $moyenneTT += $moyenne;

                                                                $nbUE ++;
                                                                $nbUET ++;


                                                                $creditT += $ec->creditMatiere;
                                                                $creditTT += $ec->creditMatiere;

                                                                if($moyenne>=10){
                                                                    $creditRecuT += $ec->creditMatiere;
                                                                    $creditRecuTT += $ec->creditMatiere;
                                                                }


                                                            @endphp

                                                            @if($same!=$ue->codeUE))
                                                            <tr>
                                                                <td rowspan="{{ (count($ue->matiere)>0)? count($ue->matiere)+1 : 1 }}">{{ $ue->codeUE }}</td>
                                                                <td colspan="8" style="background-color: #eeeeee; font-weight: bold">{{ $ue->libelleUE }}</td>

                                                            </tr>
                                                            <tr>
                                                                <td>{{ $ec->codeMatiere }}</td>
                                                                <td>{{ $ec->libelleMatiere }}</td>
                                                                <td>{{ $notecc/0.3 }}</td>
                                                                <td>{{ $noteex/0.7 }}</td>
                                                                <td>{{ $moyenne }}</td>
                                                                <td>
                                                                    @php
                                                                        if ($moyenne>=16){
                                                                            echo "A";
                                                                        }

                                                                        if ($moyenne>=14 && $moyenne<16){
                                                                            echo "B";
                                                                        }

                                                                        if ($moyenne>=12 && $moyenne<14){
                                                                            echo "C";
                                                                        }

                                                                        if ($moyenne>=10 && $moyenne<12){
                                                                            echo "D";
                                                                        }

                                                                        if ($moyenne>=8 && $moyenne<10){
                                                                            echo "E";
                                                                        }

                                                                        if ($moyenne<8){
                                                                            echo "F";
                                                                        }
                                                                    @endphp
                                                                </td>
                                                                <td>
                                                                    @php
                                                                        if ($moyenne>=10){
                                                                            echo "AC";
                                                                        }
                                                                        if ($moyenne>=9 && $moyenne<10 ){
                                                                            echo "ACC";
                                                                        }
                                                                        if ($moyenne>=0 && $moyenne<9 ){
                                                                            echo "NA";
                                                                        }
                                                                    @endphp
                                                                </td>
                                                                <td>
                                                                    @if($moyenne>=10)
                                                                        {{ $ec->creditMatiere }}
                                                                    @else
                                                                        0
                                                                    @endif
                                                                </td>
                                                            </tr>
                                                            @php
                                                                $same=$ue->codeUE;
                                                            @endphp
                                                            @else
                                                                <tr>
                                                                    <td>{{ $ec->codeMatiere }}</td>
                                                                    <td>{{ $ec->libelleMatiere }}</td>
                                                                    <td>{{ $notecc/0.3 }}</td>
                                                                    <td>{{ $noteex/0.7 }}</td>
                                                                    <td>{{ $notecc+$noteex }}</td>
                                                                    <td>
                                                                        @php
                                                                            if ($moyenne>=18){
                                                                                echo "A+";
                                                                            }

                                                                            if ($moyenne>=16 && $moyenne<18){
                                                                                echo "A";
                                                                            }

                                                                            if ($moyenne>=14 && $moyenne<16){
                                                                                echo "B+";
                                                                            }

                                                                            if ($moyenne>=13 && $moyenne<14){
                                                                                echo "B";
                                                                            }

                                                                            if ($moyenne>=12 && $moyenne<13){
                                                                                echo "B-";
                                                                            }

                                                                            if ($moyenne>=11 && $moyenne<12){
                                                                                echo "C+";
                                                                            }

                                                                            if ($moyenne>=10 && $moyenne<11){
                                                                                echo "C";
                                                                            }

                                                                            if ($moyenne>=9 && $moyenne<10){
                                                                                echo "C-";
                                                                            }

                                                                            if ($moyenne>=8 && $moyenne<9){
                                                                                echo "D";
                                                                            }

                                                                            if ($moyenne>=6 && $moyenne<8){
                                                                                echo "E";
                                                                            }

                                                                            if ($moyenne<6){
                                                                                echo "F";
                                                                            }
                                                                        @endphp
                                                                    </td>
                                                                    <td>
                                                                        @php
                                                                            if ($moyenne>=10){
                                                                                echo "AC";
                                                                            }
                                                                            if ($moyenne>=9 && $moyenne<10 ){
                                                                                echo "ACC";
                                                                            }
                                                                            if ($moyenne>=0 && $moyenne<9 ){
                                                                                echo "NA";
                                                                            }
                                                                        @endphp
                                                                    </td>
                                                                    <td>
                                                                        @if($moyenne>=10)
                                                                            {{ $ec->creditMatiere }}
                                                                        @else
                                                                            0
                                                                        @endif
                                                                    </td>
                                                                </tr>
                                                            @endif
                                                        @endforeach
                                                    @endif

                                                @endif
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            </table>


                            <table class="table" border="box" rules="all" align="center" width="100%">
                                <tbody>
                                    <tr>
                                        <td style="text-align: center; background-color: rgb(255,226,0)">Crédit total</td>
                                        <td>{{ $creditRecuT }}/{{ $creditT }}</td>
                                        <td style="text-align: center; background-color: rgb(255,226,0)">Moyenne /20</td>
                                        <td>{{ round($moyenneT/$nbUE, 3) }}</td>
                                        <td style="text-align: center; background-color: rgb(255,226,0)">Décision</td>
                                        <td>
                                            @php
                                                if (($moyenneT/$nbUE)>=16){
                                                    echo "A";
                                                }

                                                if (($moyenneT/$nbUE)>=14 && ($moyenneT/$nbUE)<16){
                                                    echo "B";
                                                }

                                                if (($moyenneT/$nbUE)>=12 && ($moyenneT/$nbUE)<14){
                                                    echo "C";
                                                }

                                                if (($moyenneT/$nbUE)>=10 && ($moyenneT/$nbUE)<12){
                                                    echo "D";
                                                }

                                                if (($moyenneT/$nbUE)>=8 && ($moyenneT/$nbUE)<10){
                                                    echo "E";
                                                }

                                                if (($moyenneT/$nbUE)<8){
                                                    echo "F";
                                                }
                                            @endphp
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        @endif
                    @endforeach
                    <hr style="background-color: #999999; border: 1px dashed #cccccc">
                    <table class="table" border="box" rules="all" align="center" width="100%">
                        <thead>
                        <th style="text-align: center; background-color: rgb(255,226,0)">Crédit total obtenu</th>
                        <th style="text-align: center; background-color: rgb(255,226,0)">Moyenne Annuelle /20</th>
                        <th style="text-align: center; background-color: rgb(255,226,0)">Rang</th>
                        <th style="text-align: center; background-color: rgb(255,226,0)">Grade</th>
                        <th style="text-align: center; background-color: rgb(255,226,0)">Decision</th>
                        </thead>
                        <tbody>
                        <tr>
                            <td>{{ $creditRecuTT }}/{{ $creditTT }}</td>
                            <td>{{ round($moyenneTT/$nbUET, 3) }}</td>
                            <td>{{ $classement[$c->inscription_id]['rang'] }}</td>
                            <td>
                                @php
                                    if (($moyenneTT/$nbUET)>=18){
                                        echo "A+";
                                    }

                                    if (($moyenneTT/$nbUET)>=16 && ($moyenneTT/$nbUET)<18){
                                        echo "A";
                                    }

                                    if (($moyenneTT/$nbUET)>=14 && ($moyenneTT/$nbUET)<16){
                                        echo "B+";
                                    }

                                    if (($moyenneTT/$nbUET)>=13 && ($moyenneTT/$nbUET)<14){
                                        echo "B";
                                    }

                                    if (($moyenneTT/$nbUET)>=12 && ($moyenneTT/$nbUET)<13){
                                        echo "B-";
                                    }

                                    if (($moyenneTT/$nbUET)>=11 && ($moyenneTT/$nbUET)<12){
                                        echo "C+";
                                    }

                                    if (($moyenneTT/$nbUET)>=10 && ($moyenneTT/$nbUET)<11){
                                        echo "C";
                                    }

                                    if (($moyenneTT/$nbUET)>=9 && ($moyenneTT/$nbUET)<10){
                                        echo "C-";
                                    }

                                    if (($moyenneTT/$nbUET)>=8 && ($moyenneTT/$nbUET)<9){
                                        echo "D";
                                    }

                                    if (($moyenneTT/$nbUET)>=6 && ($moyenneTT/$nbUET)<8){
                                        echo "E";
                                    }

                                    if (($moyenneTT/$nbUET)<6){
                                        echo "F";
                                    }
                                @endphp
                            </td>
                            <td>
                                @php
                                    if (($moyenneTT/$nbUET)>=10){
                                        echo "Admis";
                                    }else{
                                        echo "Refusé";
                                    }
                                @endphp
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <p class="paragraphe" style="text-align:center">Décision:    AC=Acquis; ACC=Acquis par compensatione; NA=Non Acquis</p>
                    <p class="paragraphe" style="text-align:center">
                        Grade et notes sur 20:
                        A+ [18-20];  A [16-18[;
                        B+ [14-16[;  B [13-14[;  B- [12-13[;
                        C+ [11-12[;  C [10-11[;  C- [11-10[;
                        D [08-09[;  E [06-08[;  F [00-06[;
                    </p>
                    @if($i<=count($sp->choice)-1)
                        <div class="page-break"></div>
                    @endif
                @endif
            @endforeach
        @endif
    @endforeach
</main>
</body>
</html>